// AUTO-GENERATED by scripts/fetch-opendata.mjs — do not edit by hand.
// Sources: mledoze/countries (calling codes), Open-Meteo (capital timezone),
// Eurostat tec00120 (price level index, EU27=100), OECD Taxing Wages (tax wedge,
// single worker at 100% average wage), Hipolabs (universities),
// WAQI (air quality in the capital; needs WAQI_TOKEN), OpenStreetMap Overpass
// (townhalls near the capital).
// Regenerate with: WAQI_TOKEN=... node scripts/fetch-opendata.mjs

export interface CountryOpenData {
  iso2: string;
  capital: string;
  drivingSide: "left" | "right";
  callingCode: string | null;
  timezone: { name: string; offset: string } | null;
  /** Household consumption price level index, EU27_2020 = 100. EU members only. */
  priceLevelEU: { value: number; year: string } | null;
  /** Average tax wedge, single worker at 100% of the average wage, % of labour cost. */
  taxWedge: { value: number; year: string } | null;
  universities: { count: number; sample: string[] } | null;
  /** Live AQI in the capital at fetch time (US EPA scale). */
  airQuality: { aqi: number; dominant: string | null; station: string } | null;
  /** Townhall / local government office names near the capital (OpenStreetMap). */
  offices: string[] | null;
}

export const OPEN_DATA_UPDATED_AT = "2026-07-04";

export const COUNTRY_OPEN_DATA: Record<string, CountryOpenData> = {
  "Portugal": {
    "iso2": "PT",
    "capital": "Lisbon",
    "drivingSide": "right",
    "callingCode": "+351",
    "timezone": {
      "name": "Europe/Lisbon",
      "offset": "UTC+1"
    },
    "priceLevelEU": {
      "value": 86.6,
      "year": "2025"
    },
    "taxWedge": {
      "value": 39.3,
      "year": "2025"
    },
    "universities": {
      "count": 65,
      "sample": [
        "Instituto Superior de Informática e Gestão",
        "Escola Nautica Infante D. Henrique",
        "Escola Superior de Artes e Design",
        "Escola Superior de Hotelaria e Turismo do Estoril",
        "European University Portugal"
      ]
    },
    "airQuality": {
      "aqi": 55,
      "dominant": "pm25",
      "station": "Entrecampos, Lisboa, Portugal"
    },
    "offices": null
  },
  "Spain": {
    "iso2": "ES",
    "capital": "Madrid",
    "drivingSide": "right",
    "callingCode": "+34",
    "timezone": {
      "name": "Europe/Madrid",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 91.6,
      "year": "2025"
    },
    "taxWedge": {
      "value": 41.4,
      "year": "2025"
    },
    "universities": {
      "count": 96,
      "sample": [
        "Barcelona Graduate School of Economics",
        "Bircham International University",
        "Universidad de San Pablo CEU",
        "Universidad de Deusto",
        "Universidad del País Vasco"
      ]
    },
    "airQuality": {
      "aqi": 74,
      "dominant": "o3",
      "station": "Madrid"
    },
    "offices": [
      "Junta Municipal de Hortaleza",
      "Agencia Tributaria Madrid",
      "Palacio de Cibeles - Ayuntamiento de Madrid",
      "Junta Municipal de Distrito de Fuencarral-El Pardo.",
      "Junta Municipal de Distrito de La Latina."
    ]
  },
  "Germany": {
    "iso2": "DE",
    "capital": "Berlin",
    "drivingSide": "right",
    "callingCode": "+49",
    "timezone": {
      "name": "Europe/Berlin",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 108.3,
      "year": "2025"
    },
    "taxWedge": {
      "value": 49.3,
      "year": "2025"
    },
    "universities": {
      "count": 320,
      "sample": [
        "IU Internationale Hochschule GmbH",
        "AKAD Hochschulen für Berufstätige, Fachhochschule Leipzig",
        "Alice-Salomon-Fachhochschule für Sozialarbeit und Sozialpädagogik Berlin",
        "Augustana Hochschule Neuendettelsau",
        "Kirchliche Hochschule Bethel"
      ]
    },
    "airQuality": {
      "aqi": 29,
      "dominant": "o3",
      "station": "Berlin, Germany"
    },
    "offices": [
      "Rathaus Treptow",
      "Rathaus Mitte",
      "Rathaus Tempelhof",
      "Rathaus Schmargendorf",
      "Rathaus Reinickendorf"
    ]
  },
  "Netherlands": {
    "iso2": "NL",
    "capital": "Amsterdam",
    "drivingSide": "right",
    "callingCode": "+31",
    "timezone": {
      "name": "Europe/Amsterdam",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 115.6,
      "year": "2025"
    },
    "taxWedge": {
      "value": 35.9,
      "year": "2025"
    },
    "universities": {
      "count": 48,
      "sample": [
        "University of Sint Eustatius School of Medicine",
        "International University School of Medicine (IUSOM)",
        "St.James's School of Medicine, Bonaire",
        "University of the Netherlands Antilles, Curacao",
        "Dutch Delta University"
      ]
    },
    "airQuality": {
      "aqi": 28,
      "dominant": "o3",
      "station": "Amsterdam"
    },
    "offices": [
      "Stadsdeel Nieuw-West",
      "Stadsloket Zuidoost",
      "Stadsloket Oost",
      "Stadsloket Noord",
      "Stadsloket West"
    ]
  },
  "France": {
    "iso2": "FR",
    "capital": "Paris",
    "drivingSide": "right",
    "callingCode": "+33",
    "timezone": {
      "name": "Europe/Paris",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 110.3,
      "year": "2025"
    },
    "taxWedge": {
      "value": 47.2,
      "year": "2025"
    },
    "universities": {
      "count": 294,
      "sample": [
        "National Institute of Applied Sciences of Toulouse",
        "IÉSEG School of Management",
        "Central Supélec",
        "Académie de Paris",
        "Académie d'Aix-Marseille"
      ]
    },
    "airQuality": {
      "aqi": 25,
      "dominant": "pm25",
      "station": "Paris"
    },
    "offices": [
      "Mairie de Clamart",
      "Mairie de Joinville-le-Pont",
      "Mairie Annexe",
      "Mairie annexe Les Hauts d'Asnières",
      "Mairie de Quartier de Bécon"
    ]
  },
  "Italy": {
    "iso2": "IT",
    "capital": "Rome",
    "drivingSide": "right",
    "callingCode": "+39",
    "timezone": {
      "name": "Europe/Rome",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 97.1,
      "year": "2025"
    },
    "taxWedge": {
      "value": 45.8,
      "year": "2025"
    },
    "universities": {
      "count": 93,
      "sample": [
        "Pontificia Università S. Tommaso",
        "Pontificio Ateneo Antonianum",
        "University of Modena",
        "Abdus Salam international centre for theoretical physics",
        "Institute for Advanced Studies Lucca"
      ]
    },
    "airQuality": {
      "aqi": 25,
      "dominant": "pm25",
      "station": "Arenula, Roma, Lazio, Italy"
    },
    "offices": [
      "Municipio IV",
      "Municipio Roma XIV",
      "LabPuzzle!",
      "Municipio II",
      "Municipio Roma I"
    ]
  },
  "Ireland": {
    "iso2": "IE",
    "capital": "Dublin",
    "drivingSide": "left",
    "callingCode": "+353",
    "timezone": {
      "name": "Europe/Dublin",
      "offset": "UTC+1"
    },
    "priceLevelEU": {
      "value": 136.2,
      "year": "2025"
    },
    "taxWedge": {
      "value": 32.6,
      "year": "2025"
    },
    "universities": {
      "count": 27,
      "sample": [
        "Athlone Institute of Technology",
        "Cork Institute of Technology",
        "Dublin City University",
        "Dublin Institute for Advanced Studies",
        "Dublin Institute of Technology"
      ]
    },
    "airQuality": {
      "aqi": 18,
      "dominant": "pm25",
      "station": "Pearse Street, Dublin 2, Ireland"
    },
    "offices": [
      "Dublin City Hall",
      "The Mansion House",
      "Ballymun Civic Centre",
      "Dublin City Council"
    ]
  },
  "United Kingdom": {
    "iso2": "GB",
    "capital": "London",
    "drivingSide": "left",
    "callingCode": "+44",
    "timezone": {
      "name": "Europe/London",
      "offset": "UTC+1"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 32.4,
      "year": "2025"
    },
    "universities": {
      "count": 192,
      "sample": [
        "West Herts College",
        "Royal Holloway University of London",
        "University of Portsmouth",
        "Futureworks",
        "University of the Arts London"
      ]
    },
    "airQuality": {
      "aqi": 23,
      "dominant": "pm25",
      "station": "London"
    },
    "offices": [
      "Westminster City Hall",
      "Islington Town Hall",
      "St Georges Town Hall",
      "Camden Town Hall",
      "St Olave's Parish Hall"
    ]
  },
  "United States": {
    "iso2": "US",
    "capital": "Washington, D.C.",
    "drivingSide": "right",
    "callingCode": "+1",
    "timezone": {
      "name": "America/New_York",
      "offset": "UTC-4"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 30,
      "year": "2025"
    },
    "universities": {
      "count": 2337,
      "sample": [
        "Marywood University",
        "Lindenwood University",
        "Sullivan University",
        "Florida State College at Jacksonville",
        "Xavier University"
      ]
    },
    "airQuality": {
      "aqi": 33,
      "dominant": "pm25",
      "station": "Aurora Hills Visitor Center, Northern Virginia, USA"
    },
    "offices": [
      "Takoma Park City Hall",
      "Friendship Heights Village Center",
      "Old City Hall",
      "John A. Wilson Building",
      "Somerset Town Hall"
    ]
  },
  "Canada": {
    "iso2": "CA",
    "capital": "Ottawa",
    "drivingSide": "right",
    "callingCode": "+1",
    "timezone": {
      "name": "America/Toronto",
      "offset": "UTC-4"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 32.1,
      "year": "2025"
    },
    "universities": {
      "count": 156,
      "sample": [
        "Toronto Baptist Seminary and Bible College",
        "Cégep de Saint-Jérôme",
        "Lambton College",
        "Acadia University",
        "Algonquin College"
      ]
    },
    "airQuality": {
      "aqi": 25,
      "dominant": "pm25",
      "station": "Ottawa"
    },
    "offices": [
      "Ben Franklin Place Client Service Centre",
      "Ottawa City Hall Heritage Building",
      "Ottawa City Hall",
      "Édifice Pierre-Papin",
      "Hôtel de Ville de Gatineau"
    ]
  },
  "Australia": {
    "iso2": "AU",
    "capital": "Canberra",
    "drivingSide": "left",
    "callingCode": "+61",
    "timezone": {
      "name": "Australia/Sydney",
      "offset": "UTC+10"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 59,
      "sample": [
        "Engineering Institute of Technology",
        "Australian Correspondence Schools",
        "Australian Catholic University",
        "University of Adelaide",
        "Australian Defence Force Academy"
      ]
    },
    "airQuality": {
      "aqi": 1,
      "dominant": "o3",
      "station": "Civic, Canberra"
    },
    "offices": [
      "Canberra Bridge Club"
    ]
  },
  "United Arab Emirates": {
    "iso2": "AE",
    "capital": "Abu Dhabi",
    "drivingSide": "right",
    "callingCode": "+971",
    "timezone": {
      "name": "Asia/Dubai",
      "offset": "UTC+4"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 37,
      "sample": [
        "Mohamed bin Zayed University of Artificial Intelligence (MBZUAI)",
        "American College Of Dubai",
        "Abu Dhabi University",
        "Al Ghurair University",
        "Ajman University"
      ]
    },
    "airQuality": {
      "aqi": 106,
      "dominant": "pm10",
      "station": "Abu Dhabi City/Kalifah High School, UAE"
    },
    "offices": null
  },
  "Estonia": {
    "iso2": "EE",
    "capital": "Tallinn",
    "drivingSide": "right",
    "callingCode": "+372",
    "timezone": {
      "name": "Europe/Tallinn",
      "offset": "UTC+3"
    },
    "priceLevelEU": {
      "value": 101.2,
      "year": "2025"
    },
    "taxWedge": {
      "value": 42.6,
      "year": "2025"
    },
    "universities": {
      "count": 10,
      "sample": [
        "Estonian Academy of Arts",
        "Estonian Business School",
        "Estonian Academy of Music and Theatre",
        "Estonian University of Life Sciences",
        "Tartu Health Care College"
      ]
    },
    "airQuality": {
      "aqi": 25,
      "dominant": "o3",
      "station": "Liivalaia, Estonia"
    },
    "offices": [
      "Linnavolikogu",
      "Tallinna Linnavalitsus",
      "Haabersti Linnaosa Valitsus",
      "Nõmme linnaosa valitsus",
      "Pirita Linnaosa Valitsus"
    ]
  },
  "Poland": {
    "iso2": "PL",
    "capital": "Warsaw",
    "drivingSide": "right",
    "callingCode": "+48",
    "timezone": {
      "name": "Europe/Warsaw",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 73.3,
      "year": "2025"
    },
    "taxWedge": {
      "value": 35,
      "year": "2025"
    },
    "universities": {
      "count": 138,
      "sample": [
        "Wroclaw Akademia Biznesu",
        "Zachodniopomorska School of Science and Engineering",
        "Vistula University",
        "Fine Arts Academy \"Jan Matejko\" in Cracow",
        "Academy of Economics in Katowice"
      ]
    },
    "airQuality": {
      "aqi": 65,
      "dominant": "pm25",
      "station": "Marszałkowska, Warszawa, Mazowieckie, Poland"
    },
    "offices": null
  },
  "Mexico": {
    "iso2": "MX",
    "capital": "Mexico City",
    "drivingSide": "right",
    "callingCode": "+52",
    "timezone": {
      "name": "America/Mexico_City",
      "offset": "UTC-6"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 21.7,
      "year": "2025"
    },
    "universities": {
      "count": 166,
      "sample": [
        "Universidad Anáhuac",
        "Universidad de La Salle, Bajío",
        "Benemerita Universidad Autónoma de Puebla",
        "Universidad de Guanajuato, Campus León",
        "Centro de Enseñanza Técnica Industrial"
      ]
    },
    "airQuality": {
      "aqi": 97,
      "dominant": "pm25",
      "station": "Merced, México, Mexico"
    },
    "offices": [
      "Delegación Iztacalco",
      "Alcaldía Coyoacán",
      "Of Departamento de Limpia",
      "ODAPAS Nezahualcoyotl",
      "Gobierno de la Ciudad de México"
    ]
  },
  "Thailand": {
    "iso2": "TH",
    "capital": "Bangkok",
    "drivingSide": "left",
    "callingCode": "+66",
    "timezone": {
      "name": "Asia/Bangkok",
      "offset": "UTC+7"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 67,
      "sample": [
        "Asian Institute of Technology",
        "Asia-Pacific International University",
        "Phranakhon Si Ayutthaya Rajabhat University",
        "Asian University of Science and Technology",
        "Assumption University of Thailand"
      ]
    },
    "airQuality": {
      "aqi": 53,
      "dominant": "pm25",
      "station": "Bangkok"
    },
    "offices": [
      "Ratchathewi District Office",
      "Pom Prap Sattru Phai District Office",
      "Bang Sue District Office",
      "Taling Chan District Office",
      "Phasi Charoen District Office"
    ]
  },
  "Japan": {
    "iso2": "JP",
    "capital": "Tokyo",
    "drivingSide": "left",
    "callingCode": "+81",
    "timezone": {
      "name": "Asia/Tokyo",
      "offset": "UTC+9"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 33.1,
      "year": "2025"
    },
    "universities": {
      "count": 570,
      "sample": [
        "Aichi Shukutoku University",
        "Aichi Bunkyo University",
        "Aichi University of Education",
        "Aichi Prefectural University of Fine Arts & Music",
        "Aichi Gakuin University"
      ]
    },
    "airQuality": {
      "aqi": 30,
      "dominant": "pm25",
      "station": "Meguro (目黒)"
    },
    "offices": null
  },
  "Singapore": {
    "iso2": "SG",
    "capital": "Singapore",
    "drivingSide": "left",
    "callingCode": "+65",
    "timezone": {
      "name": "Asia/Singapore",
      "offset": "UTC+8"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 18,
      "sample": [
        "Aventis School of Management",
        "Nanyang Technological University",
        "National University of Singapore",
        "yale-NUS",
        "Singapore Institute of Management (SIM)"
      ]
    },
    "airQuality": {
      "aqi": 61,
      "dominant": "pm25",
      "station": "South, Singapore"
    },
    "offices": [
      "Bukit Merah Branch Office",
      "Holland-Bukit Panjang Town Council (Bangkit Office)",
      "Ang Mo Kio Town Council (Avenue 1 Office)"
    ]
  }
};
