// AUTO-GENERATED by scripts/fetch-opendata.mjs — do not edit by hand.
// Sources: mledoze/countries (calling codes), Open-Meteo (capital timezone),
// Eurostat tec00120 (price level index, EU27=100), OECD Taxing Wages (tax wedge,
// single worker at 100% average wage), Hipolabs (universities),
// WAQI (air quality in the capital; needs WAQI_TOKEN), OpenStreetMap Overpass
// (townhalls near the capital).
// Regenerate with: WAQI_TOKEN=... node scripts/fetch-opendata.mjs

export interface CountryOpenData {
  iso2: string;
  capital: string;
  drivingSide: "left" | "right";
  callingCode: string | null;
  timezone: { name: string; offset: string } | null;
  /** Household consumption price level index, EU27_2020 = 100. EU members only. */
  priceLevelEU: { value: number; year: string } | null;
  /** Average tax wedge, single worker at 100% of the average wage, % of labour cost. */
  taxWedge: { value: number; year: string } | null;
  universities: { count: number; sample: string[] } | null;
  /** Live AQI in the capital at fetch time (US EPA scale). */
  airQuality: { aqi: number; dominant: string | null; station: string } | null;
  /** Townhall / local government office names near the capital (OpenStreetMap). */
  offices: string[] | null;
}

export const OPEN_DATA_UPDATED_AT = "2026-07-07";

export const COUNTRY_OPEN_DATA: Record<string, CountryOpenData> = {
  "Portugal": {
    "iso2": "PT",
    "capital": "Lisbon",
    "drivingSide": "right",
    "callingCode": "+351",
    "timezone": {
      "name": "Europe/Lisbon",
      "offset": "UTC+1"
    },
    "priceLevelEU": {
      "value": 86.6,
      "year": "2025"
    },
    "taxWedge": {
      "value": 39.3,
      "year": "2025"
    },
    "universities": {
      "count": 65,
      "sample": [
        "Instituto Superior de Informática e Gestão",
        "Escola Nautica Infante D. Henrique",
        "Escola Superior de Artes e Design",
        "Escola Superior de Hotelaria e Turismo do Estoril",
        "European University Portugal"
      ]
    },
    "airQuality": {
      "aqi": 50,
      "dominant": "pm25",
      "station": "Entrecampos, Lisboa, Portugal"
    },
    "offices": [
      "Câmara Municipal de Almada",
      "Junta de Freguesia do Lumiar",
      "Junta de Freguesia de Carnaxide",
      "União das Freguesias de Barreiro e Lavradio",
      "Junta de Freguesia da Cova da Piedade"
    ]
  },
  "Spain": {
    "iso2": "ES",
    "capital": "Madrid",
    "drivingSide": "right",
    "callingCode": "+34",
    "timezone": {
      "name": "Europe/Madrid",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 91.6,
      "year": "2025"
    },
    "taxWedge": {
      "value": 41.4,
      "year": "2025"
    },
    "universities": {
      "count": 96,
      "sample": [
        "Barcelona Graduate School of Economics",
        "Bircham International University",
        "Universidad de San Pablo CEU",
        "Universidad de Deusto",
        "Universidad del País Vasco"
      ]
    },
    "airQuality": {
      "aqi": 93,
      "dominant": "pm25",
      "station": "Madrid"
    },
    "offices": [
      "Junta Municipal de Hortaleza",
      "Agencia Tributaria Madrid",
      "Palacio de Cibeles - Ayuntamiento de Madrid",
      "Junta Municipal de Distrito de Fuencarral-El Pardo.",
      "Junta Municipal de Distrito de La Latina."
    ]
  },
  "Germany": {
    "iso2": "DE",
    "capital": "Berlin",
    "drivingSide": "right",
    "callingCode": "+49",
    "timezone": {
      "name": "Europe/Berlin",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 108.3,
      "year": "2025"
    },
    "taxWedge": {
      "value": 49.3,
      "year": "2025"
    },
    "universities": {
      "count": 320,
      "sample": [
        "IU Internationale Hochschule GmbH",
        "AKAD Hochschulen für Berufstätige, Fachhochschule Leipzig",
        "Alice-Salomon-Fachhochschule für Sozialarbeit und Sozialpädagogik Berlin",
        "Augustana Hochschule Neuendettelsau",
        "Kirchliche Hochschule Bethel"
      ]
    },
    "airQuality": {
      "aqi": 50,
      "dominant": "pm25",
      "station": "Berlin, Germany"
    },
    "offices": null
  },
  "Netherlands": {
    "iso2": "NL",
    "capital": "Amsterdam",
    "drivingSide": "right",
    "callingCode": "+31",
    "timezone": {
      "name": "Europe/Amsterdam",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 115.6,
      "year": "2025"
    },
    "taxWedge": {
      "value": 35.9,
      "year": "2025"
    },
    "universities": {
      "count": 48,
      "sample": [
        "University of Sint Eustatius School of Medicine",
        "International University School of Medicine (IUSOM)",
        "St.James's School of Medicine, Bonaire",
        "University of the Netherlands Antilles, Curacao",
        "Dutch Delta University"
      ]
    },
    "airQuality": {
      "aqi": 28,
      "dominant": "o3",
      "station": "Amsterdam"
    },
    "offices": [
      "Stadsdeel Nieuw-West",
      "Stadsloket Zuidoost",
      "Stadsloket Oost",
      "Stadsloket Noord",
      "Stadsloket West"
    ]
  },
  "France": {
    "iso2": "FR",
    "capital": "Paris",
    "drivingSide": "right",
    "callingCode": "+33",
    "timezone": {
      "name": "Europe/Paris",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 110.3,
      "year": "2025"
    },
    "taxWedge": {
      "value": 47.2,
      "year": "2025"
    },
    "universities": {
      "count": 294,
      "sample": [
        "National Institute of Applied Sciences of Toulouse",
        "IÉSEG School of Management",
        "Central Supélec",
        "Académie de Paris",
        "Académie d'Aix-Marseille"
      ]
    },
    "airQuality": {
      "aqi": 43,
      "dominant": "o3",
      "station": "Paris"
    },
    "offices": [
      "Mairie de Clamart",
      "Mairie de Joinville-le-Pont",
      "Mairie Annexe",
      "Mairie annexe Les Hauts d'Asnières",
      "Mairie de Quartier de Bécon"
    ]
  },
  "Italy": {
    "iso2": "IT",
    "capital": "Rome",
    "drivingSide": "right",
    "callingCode": "+39",
    "timezone": {
      "name": "Europe/Rome",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 97.1,
      "year": "2025"
    },
    "taxWedge": {
      "value": 45.8,
      "year": "2025"
    },
    "universities": {
      "count": 93,
      "sample": [
        "Pontificia Università S. Tommaso",
        "Pontificio Ateneo Antonianum",
        "University of Modena",
        "Abdus Salam international centre for theoretical physics",
        "Institute for Advanced Studies Lucca"
      ]
    },
    "airQuality": {
      "aqi": 25,
      "dominant": "pm25",
      "station": "Arenula, Roma, Lazio, Italy"
    },
    "offices": [
      "Municipio IV",
      "Municipio Roma XIV",
      "LabPuzzle!",
      "Municipio II",
      "Municipio Roma I"
    ]
  },
  "Ireland": {
    "iso2": "IE",
    "capital": "Dublin",
    "drivingSide": "left",
    "callingCode": "+353",
    "timezone": {
      "name": "Europe/Dublin",
      "offset": "UTC+1"
    },
    "priceLevelEU": {
      "value": 136.2,
      "year": "2025"
    },
    "taxWedge": {
      "value": 32.6,
      "year": "2025"
    },
    "universities": {
      "count": 27,
      "sample": [
        "Athlone Institute of Technology",
        "Cork Institute of Technology",
        "Dublin City University",
        "Dublin Institute for Advanced Studies",
        "Dublin Institute of Technology"
      ]
    },
    "airQuality": {
      "aqi": 35,
      "dominant": "pm25",
      "station": "Pearse Street, Dublin 2, Ireland"
    },
    "offices": [
      "Dublin City Hall",
      "The Mansion House",
      "Ballymun Civic Centre",
      "Dublin City Council"
    ]
  },
  "United Kingdom": {
    "iso2": "GB",
    "capital": "London",
    "drivingSide": "left",
    "callingCode": "+44",
    "timezone": {
      "name": "Europe/London",
      "offset": "UTC+1"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 32.4,
      "year": "2025"
    },
    "universities": {
      "count": 192,
      "sample": [
        "West Herts College",
        "Royal Holloway University of London",
        "University of Portsmouth",
        "Futureworks",
        "University of the Arts London"
      ]
    },
    "airQuality": {
      "aqi": 35,
      "dominant": "o3",
      "station": "London"
    },
    "offices": [
      "Westminster City Hall",
      "Islington Town Hall",
      "St Georges Town Hall",
      "Camden Town Hall",
      "St Olave's Parish Hall"
    ]
  },
  "United States": {
    "iso2": "US",
    "capital": "Washington, D.C.",
    "drivingSide": "right",
    "callingCode": "+1",
    "timezone": {
      "name": "America/New_York",
      "offset": "UTC-4"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 30,
      "year": "2025"
    },
    "universities": {
      "count": 2337,
      "sample": [
        "Marywood University",
        "Lindenwood University",
        "Sullivan University",
        "Florida State College at Jacksonville",
        "Xavier University"
      ]
    },
    "airQuality": {
      "aqi": 45,
      "dominant": "pm25",
      "station": "Aurora Hills Visitor Center, Northern Virginia, USA"
    },
    "offices": [
      "Takoma Park City Hall",
      "Friendship Heights Village Center",
      "Old City Hall",
      "John A. Wilson Building",
      "Somerset Town Hall"
    ]
  },
  "Canada": {
    "iso2": "CA",
    "capital": "Ottawa",
    "drivingSide": "right",
    "callingCode": "+1",
    "timezone": {
      "name": "America/Toronto",
      "offset": "UTC-4"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 32.1,
      "year": "2025"
    },
    "universities": {
      "count": 156,
      "sample": [
        "Toronto Baptist Seminary and Bible College",
        "Cégep de Saint-Jérôme",
        "Lambton College",
        "Acadia University",
        "Algonquin College"
      ]
    },
    "airQuality": {
      "aqi": 42,
      "dominant": "pm25",
      "station": "Ottawa"
    },
    "offices": [
      "Ben Franklin Place Client Service Centre",
      "Ottawa City Hall Heritage Building",
      "Ottawa City Hall",
      "Édifice Pierre-Papin",
      "Hôtel de Ville de Gatineau"
    ]
  },
  "Australia": {
    "iso2": "AU",
    "capital": "Canberra",
    "drivingSide": "left",
    "callingCode": "+61",
    "timezone": {
      "name": "Australia/Sydney",
      "offset": "UTC+10"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 27.9,
      "year": "2025"
    },
    "universities": {
      "count": 59,
      "sample": [
        "Engineering Institute of Technology",
        "Australian Correspondence Schools",
        "Australian Catholic University",
        "University of Adelaide",
        "Australian Defence Force Academy"
      ]
    },
    "airQuality": {
      "aqi": 2,
      "dominant": "o3",
      "station": "Civic, Canberra"
    },
    "offices": [
      "Canberra Bridge Club"
    ]
  },
  "United Arab Emirates": {
    "iso2": "AE",
    "capital": "Abu Dhabi",
    "drivingSide": "right",
    "callingCode": "+971",
    "timezone": {
      "name": "Asia/Dubai",
      "offset": "UTC+4"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 37,
      "sample": [
        "Mohamed bin Zayed University of Artificial Intelligence (MBZUAI)",
        "American College Of Dubai",
        "Abu Dhabi University",
        "Al Ghurair University",
        "Ajman University"
      ]
    },
    "airQuality": {
      "aqi": 85,
      "dominant": "pm25",
      "station": "Abu Dhabi City/Kalifah High School, UAE"
    },
    "offices": null
  },
  "Estonia": {
    "iso2": "EE",
    "capital": "Tallinn",
    "drivingSide": "right",
    "callingCode": "+372",
    "timezone": {
      "name": "Europe/Tallinn",
      "offset": "UTC+3"
    },
    "priceLevelEU": {
      "value": 101.2,
      "year": "2025"
    },
    "taxWedge": {
      "value": 42.6,
      "year": "2025"
    },
    "universities": {
      "count": 10,
      "sample": [
        "Estonian Academy of Arts",
        "Estonian Business School",
        "Estonian Academy of Music and Theatre",
        "Estonian University of Life Sciences",
        "Tartu Health Care College"
      ]
    },
    "airQuality": {
      "aqi": 10,
      "dominant": "o3",
      "station": "Liivalaia, Estonia"
    },
    "offices": [
      "Linnavolikogu",
      "Tallinna Linnavalitsus",
      "Haabersti Linnaosa Valitsus",
      "Nõmme linnaosa valitsus",
      "Pirita Linnaosa Valitsus"
    ]
  },
  "Poland": {
    "iso2": "PL",
    "capital": "Warsaw",
    "drivingSide": "right",
    "callingCode": "+48",
    "timezone": {
      "name": "Europe/Warsaw",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 73.3,
      "year": "2025"
    },
    "taxWedge": {
      "value": 35,
      "year": "2025"
    },
    "universities": {
      "count": 138,
      "sample": [
        "Wroclaw Akademia Biznesu",
        "Zachodniopomorska School of Science and Engineering",
        "Vistula University",
        "Fine Arts Academy \"Jan Matejko\" in Cracow",
        "Academy of Economics in Katowice"
      ]
    },
    "airQuality": {
      "aqi": 52,
      "dominant": "pm25",
      "station": "Targówek, Warszawa, Mazowieckie, Poland"
    },
    "offices": [
      "Urząd Dzielnicy Ochota",
      "Urząd Dzielnicy Bemowo",
      "Urząd Dzielnicy Praga-Południe",
      "Urząd Dzielnicy Ursus",
      "Urząd Dzielnicy Praga-Północ"
    ]
  },
  "Mexico": {
    "iso2": "MX",
    "capital": "Mexico City",
    "drivingSide": "right",
    "callingCode": "+52",
    "timezone": {
      "name": "America/Mexico_City",
      "offset": "UTC-6"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 21.7,
      "year": "2025"
    },
    "universities": {
      "count": 166,
      "sample": [
        "Universidad Anáhuac",
        "Universidad de La Salle, Bajío",
        "Benemerita Universidad Autónoma de Puebla",
        "Universidad de Guanajuato, Campus León",
        "Centro de Enseñanza Técnica Industrial"
      ]
    },
    "airQuality": {
      "aqi": 83,
      "dominant": "o3",
      "station": "Merced, México, Mexico"
    },
    "offices": [
      "Delegación Iztacalco",
      "Alcaldía Coyoacán",
      "Of Departamento de Limpia",
      "ODAPAS Nezahualcoyotl",
      "Gobierno de la Ciudad de México"
    ]
  },
  "Thailand": {
    "iso2": "TH",
    "capital": "Bangkok",
    "drivingSide": "left",
    "callingCode": "+66",
    "timezone": {
      "name": "Asia/Bangkok",
      "offset": "UTC+7"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 67,
      "sample": [
        "Asian Institute of Technology",
        "Asia-Pacific International University",
        "Phranakhon Si Ayutthaya Rajabhat University",
        "Asian University of Science and Technology",
        "Assumption University of Thailand"
      ]
    },
    "airQuality": {
      "aqi": 57,
      "dominant": "pm25",
      "station": "Bangkok"
    },
    "offices": [
      "Ratchathewi District Office",
      "Pom Prap Sattru Phai District Office",
      "Bang Sue District Office",
      "Taling Chan District Office",
      "Phasi Charoen District Office"
    ]
  },
  "Japan": {
    "iso2": "JP",
    "capital": "Tokyo",
    "drivingSide": "left",
    "callingCode": "+81",
    "timezone": {
      "name": "Asia/Tokyo",
      "offset": "UTC+9"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 33.1,
      "year": "2025"
    },
    "universities": {
      "count": 570,
      "sample": [
        "Aichi Shukutoku University",
        "Aichi Bunkyo University",
        "Aichi University of Education",
        "Aichi Prefectural University of Fine Arts & Music",
        "Aichi Gakuin University"
      ]
    },
    "airQuality": {
      "aqi": 25,
      "dominant": "pm25",
      "station": "Meguro (目黒)"
    },
    "offices": [
      "Kita City Office",
      "世田谷区 桜丘区民センター",
      "都税事務所",
      "杉並区高井戸駅前事務所宮前分室",
      "新宿区立元気館"
    ]
  },
  "Singapore": {
    "iso2": "SG",
    "capital": "Singapore",
    "drivingSide": "left",
    "callingCode": "+65",
    "timezone": {
      "name": "Asia/Singapore",
      "offset": "UTC+8"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 18,
      "sample": [
        "Aventis School of Management",
        "Nanyang Technological University",
        "National University of Singapore",
        "yale-NUS",
        "Singapore Institute of Management (SIM)"
      ]
    },
    "airQuality": {
      "aqi": 50,
      "dominant": "pm25",
      "station": "South, Singapore"
    },
    "offices": [
      "Bukit Merah Branch Office",
      "Holland-Bukit Panjang Town Council (Bangkit Office)",
      "Ang Mo Kio Town Council (Avenue 1 Office)"
    ]
  },
  "Greece": {
    "iso2": "GR",
    "capital": "Athens",
    "drivingSide": "right",
    "callingCode": "+30",
    "timezone": {
      "name": "Europe/Athens",
      "offset": "UTC+3"
    },
    "priceLevelEU": {
      "value": 87.4,
      "year": "2025"
    },
    "taxWedge": {
      "value": 39.3,
      "year": "2025"
    },
    "universities": {
      "count": 33,
      "sample": [
        "Hellenic College of Noah",
        "American College of Greece",
        "American College of Thessaloniki",
        "Aegean University",
        "School of Pedagogical and Technological Education - A.S.PAI.T.E."
      ]
    },
    "airQuality": {
      "aqi": 42,
      "dominant": "pm25",
      "station": "Aristotelous, Greece"
    },
    "offices": null
  },
  "Cyprus": {
    "iso2": "CY",
    "capital": "Nicosia",
    "drivingSide": "left",
    "callingCode": "+357",
    "timezone": {
      "name": "Asia/Nicosia",
      "offset": "UTC+3"
    },
    "priceLevelEU": {
      "value": 89.2,
      "year": "2025"
    },
    "taxWedge": null,
    "universities": {
      "count": 17,
      "sample": [
        "Americanos College",
        "Cyprus International Institute of Management (CIIM)",
        "Cyprus International University",
        "The CTL Eurocollege",
        "Cyprus University of Technology"
      ]
    },
    "airQuality": {
      "aqi": 63,
      "dominant": "pm25",
      "station": "Nicosia Traffic, Cyprus (Λευκωσία - Κυκλοφοριακός Σταθμός)"
    },
    "offices": [
      "Town Hall of Engomi",
      "Demarcheio",
      "Yeri Municipaliti Town Hall",
      "Municipality of Lefkoniko",
      "Strovolos Municipality"
    ]
  },
  "Malta": {
    "iso2": "MT",
    "capital": "Valletta",
    "drivingSide": "left",
    "callingCode": "+356",
    "timezone": {
      "name": "Europe/Malta",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 91.9,
      "year": "2025"
    },
    "taxWedge": null,
    "universities": {
      "count": 4,
      "sample": [
        "European Institute of Education",
        "International Tourism Institute",
        "Malta College of Arts, Science and Technology",
        "University of Malta"
      ]
    },
    "airQuality": {
      "aqi": 38,
      "dominant": "pm25",
      "station": "Msida, Malta"
    },
    "offices": null
  },
  "Switzerland": {
    "iso2": "CH",
    "capital": "Bern",
    "drivingSide": "right",
    "callingCode": "+41",
    "timezone": {
      "name": "Europe/Zurich",
      "offset": "UTC+2"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 23,
      "year": "2025"
    },
    "universities": {
      "count": 76,
      "sample": [
        "Schiller International University, American College of Switzerland",
        "Business and Hotel Management School",
        "Business School Lausanne (BSL)",
        "Cubidor University Switzerland",
        "DCT International Hotel & Business Management School"
      ]
    },
    "airQuality": {
      "aqi": 29,
      "dominant": "o3",
      "station": "Bern Bollwerk, Switzerland"
    },
    "offices": [
      "Gemeindeverwaltung Worb",
      "Gemeindehaus Bläuacker",
      "Gemeindevervaltung Kehrsatz",
      "Gemeindeverwaltung Bremgarten bei Bern",
      "Gemeindeverwaltung Bolligen"
    ]
  },
  "Austria": {
    "iso2": "AT",
    "capital": "Vienna",
    "drivingSide": "right",
    "callingCode": "+43",
    "timezone": {
      "name": "Europe/Vienna",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 113,
      "year": "2025"
    },
    "taxWedge": {
      "value": 47.1,
      "year": "2025"
    },
    "universities": {
      "count": 46,
      "sample": [
        "Akademie der bildenden Künste Wien",
        "Universität für Bodenkultur Wien",
        "Donau-Universität Krems",
        "Fachhochschule Burgenland",
        "Fachhochschulstudiengänge Hagenberg"
      ]
    },
    "airQuality": {
      "aqi": 7,
      "dominant": "pm10",
      "station": "Ecke Taborstraße - Glockengasse, Austria"
    },
    "offices": [
      "Amtshaus Donaustadt",
      "Magistratisches Bezirksamt für den 4. und 5. Bezirk",
      "Magistratisches Bezirksamt, 10.Bezirk (1100 Wien)",
      "Magistratisches Bezirksamt Döbling, Servicestelle",
      "Bezirksvorstehung Penzing"
    ]
  },
  "Czechia": {
    "iso2": "CZ",
    "capital": "Prague",
    "drivingSide": "right",
    "callingCode": "+420",
    "timezone": {
      "name": "Europe/Prague",
      "offset": "UTC+2"
    },
    "priceLevelEU": {
      "value": 89.4,
      "year": "2025"
    },
    "taxWedge": {
      "value": 41.2,
      "year": "2025"
    },
    "universities": null,
    "airQuality": {
      "aqi": 30,
      "dominant": "o3",
      "station": "Pha8-Karlin, Prague, Czech Republic"
    },
    "offices": null
  },
  "Georgia": {
    "iso2": "GE",
    "capital": "Tbilisi",
    "drivingSide": "right",
    "callingCode": "+995",
    "timezone": {
      "name": "Asia/Tbilisi",
      "offset": "UTC+4"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 15,
      "sample": [
        "Akaki Tsereteli State University",
        "Caucasus University",
        "European School of Management - Tbilisi",
        "University of Grigol Robakidze",
        "Georgian Agricultural University"
      ]
    },
    "airQuality": {
      "aqi": 18,
      "dominant": "pm25",
      "station": "David Agmashenebeli Avenue 73a, Tbilisi, Georgia"
    },
    "offices": [
      "Teleti Town Hall",
      "Tbilisi City Hall"
    ]
  },
  "Armenia": {
    "iso2": "AM",
    "capital": "Yerevan",
    "drivingSide": "right",
    "callingCode": "+374",
    "timezone": {
      "name": "Asia/Yerevan",
      "offset": "UTC+4"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 12,
      "sample": [
        "Mehrabyan Medical Institute and Medical College",
        "Armenian State Agrarian University",
        "Armenian State University of Economics",
        "American University of Armenia",
        "Eurasia International University"
      ]
    },
    "airQuality": {
      "aqi": 44,
      "dominant": "pm25",
      "station": "Yerevan US Embassy, Armenia"
    },
    "offices": [
      "Yerevan Municipality",
      "Zovuni Administration",
      "Shengavit Municipality",
      "Yerevan Center Municipality",
      "Kasakh MUNICIPALITY"
    ]
  },
  "Turkey": {
    "iso2": "TR",
    "capital": "Ankara",
    "drivingSide": "right",
    "callingCode": "+90",
    "timezone": {
      "name": "Europe/Istanbul",
      "offset": "UTC+3"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 40.3,
      "year": "2025"
    },
    "universities": null,
    "airQuality": {
      "aqi": 55,
      "dominant": "pm10",
      "station": "Sıhhıye, Turkey"
    },
    "offices": [
      "Güzeltepe Mahallesi Muhtarlığı",
      "Birlik Mahallesi Muhtarlığı",
      "Keçiören Belediyesi",
      "Mamak Belediyesi",
      "Ankara Büyükşehir Belediyesi"
    ]
  },
  "Brazil": {
    "iso2": "BR",
    "capital": "Brasília",
    "drivingSide": "right",
    "callingCode": "+55",
    "timezone": {
      "name": "America/Sao_Paulo",
      "offset": "UTC-3"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 187,
      "sample": [
        "Fundação Hermínio Ometto",
        "Universidade Comunitária da Região de Chapecó - Unochapecó",
        "Centro Universitário de Brasília, UNICEUB",
        "Centro Universitário Barao de Maua",
        "Universidade Braz Cubas"
      ]
    },
    "airQuality": null,
    "offices": [
      "Prefeitura da SQN 308",
      "Administração SQNW 108"
    ]
  },
  "Argentina": {
    "iso2": "AR",
    "capital": "Buenos Aires",
    "drivingSide": "right",
    "callingCode": "+54",
    "timezone": {
      "name": "America/Argentina/Buenos_Aires",
      "offset": "UTC-3"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 121,
      "sample": [
        "Universidad Atlántida Argentina",
        "Universidad Austral Buenos Aires",
        "Universidad CAECE, Buenos Aires",
        "Universidad del CEMA",
        "Instituto de Enseñanza Superior del Ejército"
      ]
    },
    "airQuality": null,
    "offices": null
  },
  "Uruguay": {
    "iso2": "UY",
    "capital": "Montevideo",
    "drivingSide": "right",
    "callingCode": "+598",
    "timezone": {
      "name": "America/Montevideo",
      "offset": "UTC-3"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 6,
      "sample": [
        "Insituto Universitario - Centro Latinoamericano de Economia Humana - IU Claeh",
        "Universidad ORT Uruguay",
        "Universidad Católica del Uruguay",
        "Universidad de la Empresa (UDE)",
        "Universidad de Montevideo"
      ]
    },
    "airQuality": null,
    "offices": [
      "Centro Comunal Zonal 16",
      "Intendencia de Montevideo"
    ]
  },
  "Costa Rica": {
    "iso2": "CR",
    "capital": "San José",
    "drivingSide": "right",
    "callingCode": "+506",
    "timezone": {
      "name": "America/Costa_Rica",
      "offset": "UTC-6"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 27.7,
      "year": "2025"
    },
    "universities": {
      "count": 32,
      "sample": [
        "Universidad Fundepos Alma Mater",
        "Universidad Isaac Newton",
        "Instituto Tecnológico de Costa Rica",
        "Universidad San Juan de la Cruz",
        "Universidad Autónoma de Centro América"
      ]
    },
    "airQuality": {
      "aqi": 21,
      "dominant": "o3",
      "station": "San Jose - Jackson St, Santa Clara, California"
    },
    "offices": [
      "Instituto Biblico",
      "topcanto.com",
      "Municipalidad de Montes de Oca",
      "Municipalidad de San José",
      "Municipalidad de Moravia"
    ]
  },
  "Panama": {
    "iso2": "PA",
    "capital": "Panama City",
    "drivingSide": "right",
    "callingCode": "+507",
    "timezone": {
      "name": "America/Panama",
      "offset": "UTC-5"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 17,
      "sample": [
        "Columbus University",
        "Floret Global University",
        "Instituto de Enseñanza Superior Oteima",
        "Universidad Tecnológica Oteima",
        "Universidad de Cartago"
      ]
    },
    "airQuality": {
      "aqi": 13,
      "dominant": "o3",
      "station": "St. Andrews State Park, Bay, Florida, USA"
    },
    "offices": [
      "Junta Comunal Victoriano Lorenzo",
      "Junta Comunal de Mateo Iturralde",
      "Junta Comunal de José Domingo Espinar",
      "Zona A - Pacìfico [AAUD]",
      "MOP"
    ]
  },
  "Colombia": {
    "iso2": "CO",
    "capital": "Bogotá",
    "drivingSide": "right",
    "callingCode": "+57",
    "timezone": {
      "name": "America/Bogota",
      "offset": "UTC-5"
    },
    "priceLevelEU": null,
    "taxWedge": {
      "value": 0,
      "year": "2025"
    },
    "universities": {
      "count": 104,
      "sample": [
        "Antonio Nariño University",
        "Universidad Autónoma de Manizales",
        "Universidad Bellas Artes",
        "Conservatorio del Tolima",
        "Colegio de Estudios Superiores de Administración (CESA)"
      ]
    },
    "airQuality": {
      "aqi": 9,
      "dominant": "pm25",
      "station": "San Cristobal, Bogota, Colombia"
    },
    "offices": [
      "Alcaldía Local de Usaquén",
      "Junta Administradora Local de Suba",
      "Spring Wireless",
      "Salón comunal de San Fernando",
      "Alcaldía Local de Chapinero"
    ]
  },
  "Malaysia": {
    "iso2": "MY",
    "capital": "Kuala Lumpur",
    "drivingSide": "left",
    "callingCode": "+60",
    "timezone": {
      "name": "Asia/Kuala_Lumpur",
      "offset": "UTC+8"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 152,
      "sample": [
        "Asia E University",
        "Aimst University",
        "Al-Bukhari International University",
        "Asia Pacific University of Technology & Innovation (APU)",
        "Advance Tertiary College"
      ]
    },
    "airQuality": {
      "aqi": 66,
      "dominant": "pm25",
      "station": "Kuala Lumpur"
    },
    "offices": [
      "D'Buana Hall",
      "Menara MBPJ",
      "Kuala Lumpur City Hall"
    ]
  },
  "Indonesia": {
    "iso2": "ID",
    "capital": "Jakarta",
    "drivingSide": "left",
    "callingCode": "+62",
    "timezone": {
      "name": "Asia/Jakarta",
      "offset": "UTC+7"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 192,
      "sample": [
        "Universitas Nusa Putra",
        "Akademi Farmasi Mitra Sehat Mandiri Sidoarjo",
        "Institut Sains & Teknologi Akprind",
        "STMIK AMIKOM Yogyakarta",
        "STIKES RS Anwar Medika"
      ]
    },
    "airQuality": {
      "aqi": 100,
      "dominant": "pm25",
      "station": "Kemayoran, Indonesia"
    },
    "offices": [
      "Balai Serbaguna",
      "Graha Zeni AD Matraman",
      "Wisma PPAD",
      "Gedung SAS",
      "Balai Kota DKI Jakarta"
    ]
  },
  "Vietnam": {
    "iso2": "VN",
    "capital": "Hanoi",
    "drivingSide": "right",
    "callingCode": "+84",
    "timezone": {
      "name": "Asia/Bangkok",
      "offset": "UTC+7"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 9,
      "sample": [
        "Phan Chau Trinh University",
        "Duy Tan University",
        "Hanoi University",
        "Ton Duc Thang University",
        "University of Da Nang"
      ]
    },
    "airQuality": {
      "aqi": 75,
      "dominant": "pm25",
      "station": "United Nations International School of Hanoi, Vietnam (Trường Quốc tế Liên Hợp Quốc Hà Nội)"
    },
    "offices": null
  },
  "New Zealand": {
    "iso2": "NZ",
    "capital": "Wellington",
    "drivingSide": "left",
    "callingCode": "+64",
    "timezone": null,
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": {
      "count": 12,
      "sample": [
        "University of Auckland",
        "Auckland University of Technology",
        "University of Canterbury",
        "Christchurch Polytechnic Institute of Technology",
        "Lincoln University"
      ]
    },
    "airQuality": null,
    "offices": [
      "Newtown Community Hall",
      "Wellington Town Hall",
      "Ngaio Town Hall",
      "Newlands Centennial Hall"
    ]
  },
  "Russia": {
    "iso2": "RU",
    "capital": "Moscow",
    "drivingSide": "right",
    "callingCode": "+7",
    "timezone": {
      "name": "Europe/Moscow",
      "offset": "UTC+3"
    },
    "priceLevelEU": null,
    "taxWedge": null,
    "universities": null,
    "airQuality": {
      "aqi": 30,
      "dominant": "pm25",
      "station": "Spirid, Moscow, Moscow, Russia (Спиридоновка, Москва)"
    },
    "offices": [
      "Префектура ЦАО",
      "Управа района \"Рязанский\"",
      "Префектура Северного Административного округа г.Москвы",
      "Префектура ЮАО",
      "Муниципалитет Тимирязевский"
    ]
  }
};
