// AUTO-GENERATED by scripts/fetch-censorship.mjs — do not edit by hand.
// Source: OONI aggregation API (https://api.ooni.org). anomaly rate =
// anomaly_count / measurement_count over the trailing ~6 months. This is a
// graded signal of interference, not proof of a block; always shown with the
// OONI link and window. Regenerate with: node scripts/fetch-censorship.mjs

export type Reachability = "reachable" | "disrupted" | "heavily-disrupted";

export interface MessengerReachability {
  /** Human label, e.g. "Telegram". */
  app: string;
  /** Anomaly rate 0..1 over the window. */
  rate: number;
  status: Reachability;
  /** Number of OONI measurements the rate is based on. */
  measurements: number;
}

export interface CountryCensorship {
  iso2: string;
  /** OONI Explorer country page. */
  ooniUrl: string;
  window: { since: string; until: string };
  messengers: MessengerReachability[];
}

export const CENSORSHIP_UPDATED_AT = "2026-07-07";

export const COUNTRY_CENSORSHIP: Record<string, CountryCensorship> = {
  "Portugal": {
    "iso2": "PT",
    "ooniUrl": "https://explorer.ooni.org/country/PT",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.002,
        "status": "reachable",
        "measurements": 10800
      },
      {
        "app": "WhatsApp",
        "rate": 0.058,
        "status": "reachable",
        "measurements": 10819
      },
      {
        "app": "Signal",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 10797
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 10984
      }
    ]
  },
  "Spain": {
    "iso2": "ES",
    "ooniUrl": "https://explorer.ooni.org/country/ES",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.007,
        "status": "reachable",
        "measurements": 267301
      },
      {
        "app": "WhatsApp",
        "rate": 0.062,
        "status": "reachable",
        "measurements": 267121
      },
      {
        "app": "Signal",
        "rate": 0.007,
        "status": "reachable",
        "measurements": 266866
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.022,
        "status": "reachable",
        "measurements": 266694
      }
    ]
  },
  "Germany": {
    "iso2": "DE",
    "ooniUrl": "https://explorer.ooni.org/country/DE",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.021,
        "status": "reachable",
        "measurements": 184409
      },
      {
        "app": "WhatsApp",
        "rate": 0.057,
        "status": "reachable",
        "measurements": 184407
      },
      {
        "app": "Signal",
        "rate": 0.023,
        "status": "reachable",
        "measurements": 183680
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.14,
        "status": "reachable",
        "measurements": 184923
      }
    ]
  },
  "Netherlands": {
    "iso2": "NL",
    "ooniUrl": "https://explorer.ooni.org/country/NL",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.015,
        "status": "reachable",
        "measurements": 85095
      },
      {
        "app": "WhatsApp",
        "rate": 0.061,
        "status": "reachable",
        "measurements": 84313
      },
      {
        "app": "Signal",
        "rate": 0.042,
        "status": "reachable",
        "measurements": 85193
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.16,
        "status": "reachable",
        "measurements": 90030
      }
    ]
  },
  "France": {
    "iso2": "FR",
    "ooniUrl": "https://explorer.ooni.org/country/FR",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.003,
        "status": "reachable",
        "measurements": 82120
      },
      {
        "app": "WhatsApp",
        "rate": 0.062,
        "status": "reachable",
        "measurements": 82039
      },
      {
        "app": "Signal",
        "rate": 0.006,
        "status": "reachable",
        "measurements": 82080
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.048,
        "status": "reachable",
        "measurements": 82616
      }
    ]
  },
  "Italy": {
    "iso2": "IT",
    "ooniUrl": "https://explorer.ooni.org/country/IT",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.003,
        "status": "reachable",
        "measurements": 37528
      },
      {
        "app": "WhatsApp",
        "rate": 0.052,
        "status": "reachable",
        "measurements": 37566
      },
      {
        "app": "Signal",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 37493
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.011,
        "status": "reachable",
        "measurements": 37529
      }
    ]
  },
  "Ireland": {
    "iso2": "IE",
    "ooniUrl": "https://explorer.ooni.org/country/IE",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.035,
        "status": "reachable",
        "measurements": 8327
      },
      {
        "app": "WhatsApp",
        "rate": 0.04,
        "status": "reachable",
        "measurements": 8328
      },
      {
        "app": "Signal",
        "rate": 0.036,
        "status": "reachable",
        "measurements": 8360
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.047,
        "status": "reachable",
        "measurements": 8410
      }
    ]
  },
  "United Kingdom": {
    "iso2": "GB",
    "ooniUrl": "https://explorer.ooni.org/country/GB",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.015,
        "status": "reachable",
        "measurements": 98177
      },
      {
        "app": "WhatsApp",
        "rate": 0.066,
        "status": "reachable",
        "measurements": 98326
      },
      {
        "app": "Signal",
        "rate": 0.007,
        "status": "reachable",
        "measurements": 98139
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.101,
        "status": "reachable",
        "measurements": 98317
      }
    ]
  },
  "United States": {
    "iso2": "US",
    "ooniUrl": "https://explorer.ooni.org/country/US",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.009,
        "status": "reachable",
        "measurements": 427205
      },
      {
        "app": "WhatsApp",
        "rate": 0.025,
        "status": "reachable",
        "measurements": 429035
      },
      {
        "app": "Signal",
        "rate": 0.008,
        "status": "reachable",
        "measurements": 428505
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.059,
        "status": "reachable",
        "measurements": 430629
      }
    ]
  },
  "Canada": {
    "iso2": "CA",
    "ooniUrl": "https://explorer.ooni.org/country/CA",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.087,
        "status": "reachable",
        "measurements": 85186
      },
      {
        "app": "WhatsApp",
        "rate": 0.029,
        "status": "reachable",
        "measurements": 85166
      },
      {
        "app": "Signal",
        "rate": 0.123,
        "status": "reachable",
        "measurements": 85130
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.018,
        "status": "reachable",
        "measurements": 86059
      }
    ]
  },
  "Australia": {
    "iso2": "AU",
    "ooniUrl": "https://explorer.ooni.org/country/AU",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.008,
        "status": "reachable",
        "measurements": 33997
      },
      {
        "app": "WhatsApp",
        "rate": 0.025,
        "status": "reachable",
        "measurements": 34110
      },
      {
        "app": "Signal",
        "rate": 0.003,
        "status": "reachable",
        "measurements": 33952
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 34055
      }
    ]
  },
  "United Arab Emirates": {
    "iso2": "AE",
    "ooniUrl": "https://explorer.ooni.org/country/AE",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.046,
        "status": "reachable",
        "measurements": 6786
      },
      {
        "app": "WhatsApp",
        "rate": 0.07,
        "status": "reachable",
        "measurements": 6824
      },
      {
        "app": "Signal",
        "rate": 0.107,
        "status": "reachable",
        "measurements": 6795
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.016,
        "status": "reachable",
        "measurements": 6850
      }
    ]
  },
  "Estonia": {
    "iso2": "EE",
    "ooniUrl": "https://explorer.ooni.org/country/EE",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.014,
        "status": "reachable",
        "measurements": 7181
      },
      {
        "app": "WhatsApp",
        "rate": 0.062,
        "status": "reachable",
        "measurements": 7173
      },
      {
        "app": "Signal",
        "rate": 0.03,
        "status": "reachable",
        "measurements": 7131
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.03,
        "status": "reachable",
        "measurements": 7426
      }
    ]
  },
  "Poland": {
    "iso2": "PL",
    "ooniUrl": "https://explorer.ooni.org/country/PL",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.012,
        "status": "reachable",
        "measurements": 17910
      },
      {
        "app": "WhatsApp",
        "rate": 0.049,
        "status": "reachable",
        "measurements": 18487
      },
      {
        "app": "Signal",
        "rate": 0.029,
        "status": "reachable",
        "measurements": 18089
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.037,
        "status": "reachable",
        "measurements": 19133
      }
    ]
  },
  "Mexico": {
    "iso2": "MX",
    "ooniUrl": "https://explorer.ooni.org/country/MX",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.009,
        "status": "reachable",
        "measurements": 21978
      },
      {
        "app": "WhatsApp",
        "rate": 0.024,
        "status": "reachable",
        "measurements": 22103
      },
      {
        "app": "Signal",
        "rate": 0.025,
        "status": "reachable",
        "measurements": 22309
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.057,
        "status": "reachable",
        "measurements": 22354
      }
    ]
  },
  "Thailand": {
    "iso2": "TH",
    "ooniUrl": "https://explorer.ooni.org/country/TH",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.007,
        "status": "reachable",
        "measurements": 9970
      },
      {
        "app": "WhatsApp",
        "rate": 0.033,
        "status": "reachable",
        "measurements": 9979
      },
      {
        "app": "Signal",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 9944
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.039,
        "status": "reachable",
        "measurements": 9960
      }
    ]
  },
  "Japan": {
    "iso2": "JP",
    "ooniUrl": "https://explorer.ooni.org/country/JP",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.015,
        "status": "reachable",
        "measurements": 21476
      },
      {
        "app": "WhatsApp",
        "rate": 0.025,
        "status": "reachable",
        "measurements": 21444
      },
      {
        "app": "Signal",
        "rate": 0.008,
        "status": "reachable",
        "measurements": 20372
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.024,
        "status": "reachable",
        "measurements": 21509
      }
    ]
  },
  "Singapore": {
    "iso2": "SG",
    "ooniUrl": "https://explorer.ooni.org/country/SG",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.007,
        "status": "reachable",
        "measurements": 5759
      },
      {
        "app": "WhatsApp",
        "rate": 0.022,
        "status": "reachable",
        "measurements": 5754
      },
      {
        "app": "Signal",
        "rate": 0.019,
        "status": "reachable",
        "measurements": 5738
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.067,
        "status": "reachable",
        "measurements": 5758
      }
    ]
  },
  "Greece": {
    "iso2": "GR",
    "ooniUrl": "https://explorer.ooni.org/country/GR",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 7375
      },
      {
        "app": "WhatsApp",
        "rate": 0.053,
        "status": "reachable",
        "measurements": 7370
      },
      {
        "app": "Signal",
        "rate": 0.002,
        "status": "reachable",
        "measurements": 7379
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.002,
        "status": "reachable",
        "measurements": 7378
      }
    ]
  },
  "Cyprus": {
    "iso2": "CY",
    "ooniUrl": "https://explorer.ooni.org/country/CY",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.002,
        "status": "reachable",
        "measurements": 4163
      },
      {
        "app": "WhatsApp",
        "rate": 0.042,
        "status": "reachable",
        "measurements": 4173
      },
      {
        "app": "Signal",
        "rate": 0,
        "status": "reachable",
        "measurements": 4159
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.015,
        "status": "reachable",
        "measurements": 4165
      }
    ]
  },
  "Malta": {
    "iso2": "MT",
    "ooniUrl": "https://explorer.ooni.org/country/MT",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.001,
        "status": "reachable",
        "measurements": 767
      },
      {
        "app": "WhatsApp",
        "rate": 0.031,
        "status": "reachable",
        "measurements": 767
      },
      {
        "app": "Signal",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 767
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 767
      }
    ]
  },
  "Switzerland": {
    "iso2": "CH",
    "ooniUrl": "https://explorer.ooni.org/country/CH",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.007,
        "status": "reachable",
        "measurements": 22920
      },
      {
        "app": "WhatsApp",
        "rate": 0.053,
        "status": "reachable",
        "measurements": 22942
      },
      {
        "app": "Signal",
        "rate": 0.021,
        "status": "reachable",
        "measurements": 22908
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.018,
        "status": "reachable",
        "measurements": 22929
      }
    ]
  },
  "Austria": {
    "iso2": "AT",
    "ooniUrl": "https://explorer.ooni.org/country/AT",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.007,
        "status": "reachable",
        "measurements": 15705
      },
      {
        "app": "WhatsApp",
        "rate": 0.054,
        "status": "reachable",
        "measurements": 15731
      },
      {
        "app": "Signal",
        "rate": 0.025,
        "status": "reachable",
        "measurements": 15658
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.013,
        "status": "reachable",
        "measurements": 15657
      }
    ]
  },
  "Czechia": {
    "iso2": "CZ",
    "ooniUrl": "https://explorer.ooni.org/country/CZ",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 16793
      },
      {
        "app": "WhatsApp",
        "rate": 0.055,
        "status": "reachable",
        "measurements": 16774
      },
      {
        "app": "Signal",
        "rate": 0.026,
        "status": "reachable",
        "measurements": 16806
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.01,
        "status": "reachable",
        "measurements": 16967
      }
    ]
  },
  "Georgia": {
    "iso2": "GE",
    "ooniUrl": "https://explorer.ooni.org/country/GE",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.002,
        "status": "reachable",
        "measurements": 12356
      },
      {
        "app": "WhatsApp",
        "rate": 0.053,
        "status": "reachable",
        "measurements": 12363
      },
      {
        "app": "Signal",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 12318
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.006,
        "status": "reachable",
        "measurements": 12364
      }
    ]
  },
  "Armenia": {
    "iso2": "AM",
    "ooniUrl": "https://explorer.ooni.org/country/AM",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.012,
        "status": "reachable",
        "measurements": 5741
      },
      {
        "app": "WhatsApp",
        "rate": 0.061,
        "status": "reachable",
        "measurements": 5733
      },
      {
        "app": "Signal",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 5713
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.003,
        "status": "reachable",
        "measurements": 5719
      }
    ]
  },
  "Turkey": {
    "iso2": "TR",
    "ooniUrl": "https://explorer.ooni.org/country/TR",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 24392
      },
      {
        "app": "WhatsApp",
        "rate": 0.051,
        "status": "reachable",
        "measurements": 24370
      },
      {
        "app": "Signal",
        "rate": 0.007,
        "status": "reachable",
        "measurements": 24383
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.025,
        "status": "reachable",
        "measurements": 24350
      }
    ]
  },
  "Brazil": {
    "iso2": "BR",
    "ooniUrl": "https://explorer.ooni.org/country/BR",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.018,
        "status": "reachable",
        "measurements": 123580
      },
      {
        "app": "WhatsApp",
        "rate": 0.02,
        "status": "reachable",
        "measurements": 123876
      },
      {
        "app": "Signal",
        "rate": 0.007,
        "status": "reachable",
        "measurements": 123027
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.06,
        "status": "reachable",
        "measurements": 123735
      }
    ]
  },
  "Argentina": {
    "iso2": "AR",
    "ooniUrl": "https://explorer.ooni.org/country/AR",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 13607
      },
      {
        "app": "WhatsApp",
        "rate": 0.016,
        "status": "reachable",
        "measurements": 13812
      },
      {
        "app": "Signal",
        "rate": 0.002,
        "status": "reachable",
        "measurements": 13593
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 13614
      }
    ]
  },
  "Uruguay": {
    "iso2": "UY",
    "ooniUrl": "https://explorer.ooni.org/country/UY",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0,
        "status": "reachable",
        "measurements": 1149
      },
      {
        "app": "WhatsApp",
        "rate": 0.008,
        "status": "reachable",
        "measurements": 1153
      },
      {
        "app": "Signal",
        "rate": 0.002,
        "status": "reachable",
        "measurements": 1154
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.486,
        "status": "disrupted",
        "measurements": 1156
      }
    ]
  },
  "Costa Rica": {
    "iso2": "CR",
    "ooniUrl": "https://explorer.ooni.org/country/CR",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0,
        "status": "reachable",
        "measurements": 509
      },
      {
        "app": "WhatsApp",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 506
      },
      {
        "app": "Signal",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 510
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.008,
        "status": "reachable",
        "measurements": 510
      }
    ]
  },
  "Panama": {
    "iso2": "PA",
    "ooniUrl": "https://explorer.ooni.org/country/PA",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0,
        "status": "reachable",
        "measurements": 280
      },
      {
        "app": "WhatsApp",
        "rate": 0.007,
        "status": "reachable",
        "measurements": 281
      },
      {
        "app": "Signal",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 279
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 280
      }
    ]
  },
  "Colombia": {
    "iso2": "CO",
    "ooniUrl": "https://explorer.ooni.org/country/CO",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.003,
        "status": "reachable",
        "measurements": 13969
      },
      {
        "app": "WhatsApp",
        "rate": 0.016,
        "status": "reachable",
        "measurements": 13979
      },
      {
        "app": "Signal",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 13959
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 13972
      }
    ]
  },
  "Malaysia": {
    "iso2": "MY",
    "ooniUrl": "https://explorer.ooni.org/country/MY",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.005,
        "status": "reachable",
        "measurements": 19515
      },
      {
        "app": "WhatsApp",
        "rate": 0.02,
        "status": "reachable",
        "measurements": 19448
      },
      {
        "app": "Signal",
        "rate": 0.002,
        "status": "reachable",
        "measurements": 19447
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.021,
        "status": "reachable",
        "measurements": 19485
      }
    ]
  },
  "Indonesia": {
    "iso2": "ID",
    "ooniUrl": "https://explorer.ooni.org/country/ID",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 29803
      },
      {
        "app": "WhatsApp",
        "rate": 0.028,
        "status": "reachable",
        "measurements": 29788
      },
      {
        "app": "Signal",
        "rate": 0.027,
        "status": "reachable",
        "measurements": 29821
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.011,
        "status": "reachable",
        "measurements": 29835
      }
    ]
  },
  "Vietnam": {
    "iso2": "VN",
    "ooniUrl": "https://explorer.ooni.org/country/VN",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.006,
        "status": "reachable",
        "measurements": 12823
      },
      {
        "app": "WhatsApp",
        "rate": 0.023,
        "status": "reachable",
        "measurements": 12805
      },
      {
        "app": "Signal",
        "rate": 0.004,
        "status": "reachable",
        "measurements": 12813
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.011,
        "status": "reachable",
        "measurements": 12829
      }
    ]
  },
  "New Zealand": {
    "iso2": "NZ",
    "ooniUrl": "https://explorer.ooni.org/country/NZ",
    "window": {
      "since": "2026-01-05",
      "until": "2026-07-07"
    },
    "messengers": [
      {
        "app": "Telegram",
        "rate": 0.066,
        "status": "reachable",
        "measurements": 5557
      },
      {
        "app": "WhatsApp",
        "rate": 0.036,
        "status": "reachable",
        "measurements": 5569
      },
      {
        "app": "Signal",
        "rate": 0.008,
        "status": "reachable",
        "measurements": 5549
      },
      {
        "app": "Facebook Messenger",
        "rate": 0.028,
        "status": "reachable",
        "measurements": 5576
      }
    ]
  }
};
