import { normalizeName } from "@/lib/countryFacts";

// Maps each country in the autosuggest list to its ISO 4217 currency code.
// Used to convert the user's origin currency into the destination currency in
// the country snapshot card. Keyed by lowercased country name.
const COUNTRY_CURRENCY: Record<string, string> = {
  afghanistan: "AFN",
  albania: "ALL",
  algeria: "DZD",
  andorra: "EUR",
  angola: "AOA",
  argentina: "ARS",
  armenia: "AMD",
  australia: "AUD",
  austria: "EUR",
  azerbaijan: "AZN",
  bahamas: "BSD",
  bahrain: "BHD",
  bangladesh: "BDT",
  barbados: "BBD",
  belarus: "BYN",
  belgium: "EUR",
  belize: "BZD",
  benin: "XOF",
  bhutan: "BTN",
  bolivia: "BOB",
  "bosnia and herzegovina": "BAM",
  botswana: "BWP",
  brazil: "BRL",
  brunei: "BND",
  bulgaria: "BGN",
  "burkina faso": "XOF",
  burundi: "BIF",
  cambodia: "KHR",
  cameroon: "XAF",
  canada: "CAD",
  "cape verde": "CVE",
  chad: "XAF",
  chile: "CLP",
  china: "CNY",
  colombia: "COP",
  "costa rica": "CRC",
  croatia: "EUR",
  cuba: "CUP",
  cyprus: "EUR",
  czechia: "CZK",
  denmark: "DKK",
  "dominican republic": "DOP",
  ecuador: "USD",
  egypt: "EGP",
  "el salvador": "USD",
  estonia: "EUR",
  ethiopia: "ETB",
  fiji: "FJD",
  finland: "EUR",
  france: "EUR",
  georgia: "GEL",
  germany: "EUR",
  ghana: "GHS",
  greece: "EUR",
  guatemala: "GTQ",
  honduras: "HNL",
  "hong kong": "HKD",
  hungary: "HUF",
  iceland: "ISK",
  india: "INR",
  indonesia: "IDR",
  iran: "IRR",
  iraq: "IQD",
  ireland: "EUR",
  israel: "ILS",
  italy: "EUR",
  "ivory coast": "XOF",
  jamaica: "JMD",
  japan: "JPY",
  jordan: "JOD",
  kazakhstan: "KZT",
  kenya: "KES",
  kuwait: "KWD",
  kyrgyzstan: "KGS",
  laos: "LAK",
  latvia: "EUR",
  lebanon: "LBP",
  libya: "LYD",
  liechtenstein: "CHF",
  lithuania: "EUR",
  luxembourg: "EUR",
  macau: "MOP",
  madagascar: "MGA",
  malaysia: "MYR",
  maldives: "MVR",
  malta: "EUR",
  mauritius: "MUR",
  mexico: "MXN",
  moldova: "MDL",
  monaco: "EUR",
  mongolia: "MNT",
  montenegro: "EUR",
  morocco: "MAD",
  mozambique: "MZN",
  myanmar: "MMK",
  namibia: "NAD",
  nepal: "NPR",
  netherlands: "EUR",
  "new zealand": "NZD",
  nicaragua: "NIO",
  nigeria: "NGN",
  "north macedonia": "MKD",
  norway: "NOK",
  oman: "OMR",
  pakistan: "PKR",
  panama: "PAB",
  paraguay: "PYG",
  peru: "PEN",
  philippines: "PHP",
  poland: "PLN",
  portugal: "EUR",
  qatar: "QAR",
  romania: "RON",
  russia: "RUB",
  rwanda: "RWF",
  "saudi arabia": "SAR",
  senegal: "XOF",
  serbia: "RSD",
  singapore: "SGD",
  slovakia: "EUR",
  slovenia: "EUR",
  "south africa": "ZAR",
  "south korea": "KRW",
  spain: "EUR",
  "sri lanka": "LKR",
  sweden: "SEK",
  switzerland: "CHF",
  taiwan: "TWD",
  tanzania: "TZS",
  thailand: "THB",
  tunisia: "TND",
  turkey: "TRY",
  uganda: "UGX",
  ukraine: "UAH",
  "united arab emirates": "AED",
  "united kingdom": "GBP",
  "united states": "USD",
  uruguay: "UYU",
  uzbekistan: "UZS",
  venezuela: "VES",
  vietnam: "VND",
  zambia: "ZMW",
  zimbabwe: "ZWL",
};

export function currencyForCountry(country: string): string | null {
  return COUNTRY_CURRENCY[normalizeName(country)] ?? null;
}
