// AUTO-GENERATED by scripts/fetch-opendata.mjs — do not edit by hand.
// Lightweight origin layer for all countries: capital, UTC offset (hours, at
// fetch time — DST-dependent) and capital AQI (WAQI, at fetch time). Used to
// personalize destination data against the user's origin country.
// Regenerate with: WAQI_TOKEN=... node scripts/fetch-opendata.mjs

export interface CountryOrigin {
  capital: string;
  offsetHours: number | null;
  aqi: number | null;
}

export const COUNTRY_ORIGIN: Record<string, CountryOrigin> = {
  "Afghanistan": {
    "capital": "Kabul",
    "offsetHours": 4.5,
    "aqi": 74
  },
  "Andorra": {
    "capital": "Andorra la Vella",
    "offsetHours": 2,
    "aqi": 40
  },
  "Angola": {
    "capital": "Luanda",
    "offsetHours": 1,
    "aqi": 291
  },
  "Aruba": {
    "capital": "Oranjestad",
    "offsetHours": -4,
    "aqi": 53
  },
  "United Arab Emirates": {
    "capital": "Abu Dhabi",
    "offsetHours": 4,
    "aqi": 105
  },
  "Anguilla": {
    "capital": "The Valley",
    "offsetHours": -4,
    "aqi": 58
  },
  "Albania": {
    "capital": "Tirana",
    "offsetHours": 2,
    "aqi": 33
  },
  "Åland Islands": {
    "capital": "Mariehamn",
    "offsetHours": 3,
    "aqi": 26
  },
  "Armenia": {
    "capital": "Yerevan",
    "offsetHours": 4,
    "aqi": 90
  },
  "American Samoa": {
    "capital": "Pago Pago",
    "offsetHours": -11,
    "aqi": 9
  },
  "Argentina": {
    "capital": "Buenos Aires",
    "offsetHours": -3,
    "aqi": 63
  },
  "French Southern and Antarctic Lands": {
    "capital": "Port-aux-Français",
    "offsetHours": 5,
    "aqi": 20
  },
  "Antigua and Barbuda": {
    "capital": "Saint John's",
    "offsetHours": -4,
    "aqi": 32
  },
  "Australia": {
    "capital": "Canberra",
    "offsetHours": 10,
    "aqi": 1
  },
  "Azerbaijan": {
    "capital": "Baku",
    "offsetHours": 4,
    "aqi": 114
  },
  "Austria": {
    "capital": "Vienna",
    "offsetHours": 2,
    "aqi": 10
  },
  "Belgium": {
    "capital": "Brussels",
    "offsetHours": 2,
    "aqi": 27
  },
  "Benin": {
    "capital": "Porto-Novo",
    "offsetHours": 1,
    "aqi": 50
  },
  "Burundi": {
    "capital": "Gitega",
    "offsetHours": 2,
    "aqi": 48
  },
  "Burkina Faso": {
    "capital": "Ouagadougou",
    "offsetHours": 0,
    "aqi": 50
  },
  "Bahrain": {
    "capital": "Manama",
    "offsetHours": 3,
    "aqi": 76
  },
  "Bahamas": {
    "capital": "Nassau",
    "offsetHours": -4,
    "aqi": 51
  },
  "Bulgaria": {
    "capital": "Sofia",
    "offsetHours": 3,
    "aqi": 39
  },
  "Bangladesh": {
    "capital": "Dhaka",
    "offsetHours": 6,
    "aqi": null
  },
  "Bosnia and Herzegovina": {
    "capital": "Sarajevo",
    "offsetHours": 2,
    "aqi": 31
  },
  "Saint Barthélemy": {
    "capital": "Gustavia",
    "offsetHours": -4,
    "aqi": 58
  },
  "Saint Helena, Ascension and Tristan da Cunha": {
    "capital": "Jamestown",
    "offsetHours": 0,
    "aqi": 17
  },
  "Belarus": {
    "capital": "Minsk",
    "offsetHours": 3,
    "aqi": 23
  },
  "Bolivia": {
    "capital": "Sucre",
    "offsetHours": -4,
    "aqi": 41
  },
  "Bermuda": {
    "capital": "Hamilton",
    "offsetHours": -4,
    "aqi": 25
  },
  "Belize": {
    "capital": "Belmopan",
    "offsetHours": -6,
    "aqi": 25
  },
  "Caribbean Netherlands": {
    "capital": "Kralendijk",
    "offsetHours": -4,
    "aqi": 69
  },
  "Brazil": {
    "capital": "Brasília",
    "offsetHours": -3,
    "aqi": 41
  },
  "Brunei": {
    "capital": "Bandar Seri Begawan",
    "offsetHours": 8,
    "aqi": 7
  },
  "Barbados": {
    "capital": "Bridgetown",
    "offsetHours": -4,
    "aqi": 76
  },
  "Canada": {
    "capital": "Ottawa",
    "offsetHours": -4,
    "aqi": 30
  },
  "Central African Republic": {
    "capital": "Bangui",
    "offsetHours": 1,
    "aqi": 291
  },
  "Bhutan": {
    "capital": "Thimphu",
    "offsetHours": 6,
    "aqi": null
  },
  "Botswana": {
    "capital": "Gaborone",
    "offsetHours": 2,
    "aqi": 27
  },
  "Cocos (Keeling) Islands": {
    "capital": "West Island",
    "offsetHours": 6.5,
    "aqi": 160
  },
  "China": {
    "capital": "Beijing",
    "offsetHours": 8,
    "aqi": 33
  },
  "Chile": {
    "capital": "Santiago",
    "offsetHours": -4,
    "aqi": 127
  },
  "Switzerland": {
    "capital": "Bern",
    "offsetHours": 2,
    "aqi": 44
  },
  "Ivory Coast": {
    "capital": "Yamoussoukro",
    "offsetHours": 0,
    "aqi": 50
  },
  "Cook Islands": {
    "capital": "Avarua",
    "offsetHours": -10,
    "aqi": 9
  },
  "Cameroon": {
    "capital": "Yaoundé",
    "offsetHours": 1,
    "aqi": 291
  },
  "Congo": {
    "capital": "Brazzaville",
    "offsetHours": 1,
    "aqi": 291
  },
  "DR Congo": {
    "capital": "Kinshasa",
    "offsetHours": 1,
    "aqi": 291
  },
  "Comoros": {
    "capital": "Moroni",
    "offsetHours": 3,
    "aqi": 48
  },
  "Cape Verde": {
    "capital": "Praia",
    "offsetHours": -1,
    "aqi": 30
  },
  "Colombia": {
    "capital": "Bogotá",
    "offsetHours": -5,
    "aqi": 25
  },
  "Costa Rica": {
    "capital": "San José",
    "offsetHours": -6,
    "aqi": 55
  },
  "Cayman Islands": {
    "capital": "George Town",
    "offsetHours": -5,
    "aqi": 51
  },
  "Christmas Island": {
    "capital": "Flying Fish Cove",
    "offsetHours": 7,
    "aqi": 117
  },
  "Curaçao": {
    "capital": "Willemstad",
    "offsetHours": -4,
    "aqi": 66
  },
  "Cuba": {
    "capital": "Havana",
    "offsetHours": -4,
    "aqi": 43
  },
  "Czechia": {
    "capital": "Prague",
    "offsetHours": 2,
    "aqi": 32
  },
  "Germany": {
    "capital": "Berlin",
    "offsetHours": 2,
    "aqi": 42
  },
  "Cyprus": {
    "capital": "Nicosia",
    "offsetHours": 3,
    "aqi": 75
  },
  "Djibouti": {
    "capital": "Djibouti",
    "offsetHours": 3,
    "aqi": 85
  },
  "Dominica": {
    "capital": "Roseau",
    "offsetHours": -4,
    "aqi": 69
  },
  "Denmark": {
    "capital": "Copenhagen",
    "offsetHours": 2,
    "aqi": 28
  },
  "Dominican Republic": {
    "capital": "Santo Domingo",
    "offsetHours": -4,
    "aqi": 66
  },
  "Algeria": {
    "capital": "Algiers",
    "offsetHours": 1,
    "aqi": 33
  },
  "Egypt": {
    "capital": "Cairo",
    "offsetHours": 3,
    "aqi": 59
  },
  "Eritrea": {
    "capital": "Asmara",
    "offsetHours": 3,
    "aqi": 23
  },
  "Ecuador": {
    "capital": "Quito",
    "offsetHours": -5,
    "aqi": 68
  },
  "Spain": {
    "capital": "Madrid",
    "offsetHours": 2,
    "aqi": 74
  },
  "Ethiopia": {
    "capital": "Addis Ababa",
    "offsetHours": 3,
    "aqi": 68
  },
  "Estonia": {
    "capital": "Tallinn",
    "offsetHours": 3,
    "aqi": 25
  },
  "Finland": {
    "capital": "Helsinki",
    "offsetHours": 3,
    "aqi": 18
  },
  "Fiji": {
    "capital": "Suva",
    "offsetHours": 12,
    "aqi": 9
  },
  "Falkland Islands": {
    "capital": "Stanley",
    "offsetHours": -3,
    "aqi": 192
  },
  "France": {
    "capital": "Paris",
    "offsetHours": 2,
    "aqi": 52
  },
  "Faroe Islands": {
    "capital": "Tórshavn",
    "offsetHours": 1,
    "aqi": 2
  },
  "Micronesia": {
    "capital": "Palikir",
    "offsetHours": 11,
    "aqi": 20
  },
  "Georgia": {
    "capital": "Tbilisi",
    "offsetHours": 4,
    "aqi": 43
  },
  "United Kingdom": {
    "capital": "London",
    "offsetHours": 1,
    "aqi": 25
  },
  "Gabon": {
    "capital": "Libreville",
    "offsetHours": 1,
    "aqi": 291
  },
  "Ghana": {
    "capital": "Accra",
    "offsetHours": 0,
    "aqi": 50
  },
  "Guinea": {
    "capital": "Conakry",
    "offsetHours": 0,
    "aqi": 38
  },
  "Gibraltar": {
    "capital": "Gibraltar",
    "offsetHours": 2,
    "aqi": 12
  },
  "Guadeloupe": {
    "capital": "Basse-Terre",
    "offsetHours": -4,
    "aqi": 66
  },
  "Gambia": {
    "capital": "Banjul",
    "offsetHours": 0,
    "aqi": 38
  },
  "Equatorial Guinea": {
    "capital": "Malabo",
    "offsetHours": 1,
    "aqi": 49
  },
  "Greece": {
    "capital": "Athens",
    "offsetHours": 3,
    "aqi": 42
  },
  "Guinea-Bissau": {
    "capital": "Bissau",
    "offsetHours": 0,
    "aqi": 38
  },
  "Grenada": {
    "capital": "St. George's",
    "offsetHours": -4,
    "aqi": 76
  },
  "Guatemala": {
    "capital": "Guatemala City",
    "offsetHours": -6,
    "aqi": 25
  },
  "Greenland": {
    "capital": "Nuuk",
    "offsetHours": -1,
    "aqi": 34
  },
  "French Guiana": {
    "capital": "Cayenne",
    "offsetHours": -3,
    "aqi": 18
  },
  "Guam": {
    "capital": "Hagåtña",
    "offsetHours": 10,
    "aqi": 55
  },
  "Honduras": {
    "capital": "Tegucigalpa",
    "offsetHours": -6,
    "aqi": 25
  },
  "Hong Kong": {
    "capital": "City of Victoria",
    "offsetHours": -5,
    "aqi": 41
  },
  "Guyana": {
    "capital": "Georgetown",
    "offsetHours": -4,
    "aqi": 13
  },
  "Haiti": {
    "capital": "Port-au-Prince",
    "offsetHours": -4,
    "aqi": 51
  },
  "Croatia": {
    "capital": "Zagreb",
    "offsetHours": 2,
    "aqi": 17
  },
  "Hungary": {
    "capital": "Budapest",
    "offsetHours": 2,
    "aqi": 11
  },
  "Indonesia": {
    "capital": "Jakarta",
    "offsetHours": 7,
    "aqi": 117
  },
  "Isle of Man": {
    "capital": "Douglas",
    "offsetHours": 1,
    "aqi": 17
  },
  "Ireland": {
    "capital": "Dublin",
    "offsetHours": 1,
    "aqi": 18
  },
  "India": {
    "capital": "New Delhi",
    "offsetHours": 5.5,
    "aqi": 164
  },
  "Iran": {
    "capital": "Tehran",
    "offsetHours": 3.5,
    "aqi": 114
  },
  "Iraq": {
    "capital": "Baghdad",
    "offsetHours": 3,
    "aqi": 62
  },
  "Iceland": {
    "capital": "Reykjavik",
    "offsetHours": 0,
    "aqi": 8
  },
  "Israel": {
    "capital": "Jerusalem",
    "offsetHours": 3,
    "aqi": 52
  },
  "Italy": {
    "capital": "Rome",
    "offsetHours": 2,
    "aqi": 2
  },
  "Jersey": {
    "capital": "Saint Helier",
    "offsetHours": 1,
    "aqi": 19
  },
  "Jamaica": {
    "capital": "Kingston",
    "offsetHours": -5,
    "aqi": 51
  },
  "Jordan": {
    "capital": "Amman",
    "offsetHours": 3,
    "aqi": 19
  },
  "Japan": {
    "capital": "Tokyo",
    "offsetHours": 9,
    "aqi": 30
  },
  "Kazakhstan": {
    "capital": "Astana",
    "offsetHours": 5,
    "aqi": 6
  },
  "Kenya": {
    "capital": "Nairobi",
    "offsetHours": 3,
    "aqi": 48
  },
  "Kyrgyzstan": {
    "capital": "Bishkek",
    "offsetHours": 6,
    "aqi": 3
  },
  "Cambodia": {
    "capital": "Phnom Penh",
    "offsetHours": 7,
    "aqi": 3
  },
  "Saint Kitts and Nevis": {
    "capital": "Basseterre",
    "offsetHours": -4,
    "aqi": 58
  },
  "South Korea": {
    "capital": "Seoul",
    "offsetHours": 9,
    "aqi": 55
  },
  "Kuwait": {
    "capital": "Kuwait City",
    "offsetHours": 3,
    "aqi": 61
  },
  "Laos": {
    "capital": "Vientiane",
    "offsetHours": 7,
    "aqi": 55
  },
  "Lebanon": {
    "capital": "Beirut",
    "offsetHours": 3,
    "aqi": 47
  },
  "Liberia": {
    "capital": "Monrovia",
    "offsetHours": 0,
    "aqi": 38
  },
  "Libya": {
    "capital": "Tripoli",
    "offsetHours": 2,
    "aqi": 49
  },
  "Saint Lucia": {
    "capital": "Castries",
    "offsetHours": -4,
    "aqi": 76
  },
  "Sri Lanka": {
    "capital": "Colombo",
    "offsetHours": 5.5,
    "aqi": 22
  },
  "Liechtenstein": {
    "capital": "Vaduz",
    "offsetHours": 2,
    "aqi": 10
  },
  "Lesotho": {
    "capital": "Maseru",
    "offsetHours": 2,
    "aqi": 500
  },
  "Lithuania": {
    "capital": "Vilnius",
    "offsetHours": 3,
    "aqi": 23
  },
  "Latvia": {
    "capital": "Riga",
    "offsetHours": 3,
    "aqi": 24
  },
  "Luxembourg": {
    "capital": "Luxembourg",
    "offsetHours": 2,
    "aqi": 39
  },
  "Saint Martin": {
    "capital": "Marigot",
    "offsetHours": -4,
    "aqi": 58
  },
  "Morocco": {
    "capital": "Rabat",
    "offsetHours": 1,
    "aqi": 42
  },
  "Monaco": {
    "capital": "Monaco",
    "offsetHours": 2,
    "aqi": 16
  },
  "Moldova": {
    "capital": "Chișinău",
    "offsetHours": 3,
    "aqi": 27
  },
  "Madagascar": {
    "capital": "Antananarivo",
    "offsetHours": 3,
    "aqi": 12
  },
  "Maldives": {
    "capital": "Malé",
    "offsetHours": 5,
    "aqi": 22
  },
  "Mexico": {
    "capital": "Mexico City",
    "offsetHours": -6,
    "aqi": 109
  },
  "Marshall Islands": {
    "capital": "Majuro",
    "offsetHours": 12,
    "aqi": 16
  },
  "North Macedonia": {
    "capital": "Skopje",
    "offsetHours": 2,
    "aqi": 11
  },
  "Mali": {
    "capital": "Bamako",
    "offsetHours": 0,
    "aqi": 40
  },
  "Malta": {
    "capital": "Valletta",
    "offsetHours": 2,
    "aqi": 52
  },
  "Myanmar": {
    "capital": "Naypyidaw",
    "offsetHours": 6.5,
    "aqi": 24
  },
  "Montenegro": {
    "capital": "Podgorica",
    "offsetHours": 2,
    "aqi": 21
  },
  "Mongolia": {
    "capital": "Ulan Bator",
    "offsetHours": 8,
    "aqi": 33
  },
  "Northern Mariana Islands": {
    "capital": "Saipan",
    "offsetHours": 10,
    "aqi": 9
  },
  "Mozambique": {
    "capital": "Maputo",
    "offsetHours": 2,
    "aqi": 153
  },
  "Mauritania": {
    "capital": "Nouakchott",
    "offsetHours": 0,
    "aqi": 38
  },
  "Montserrat": {
    "capital": "Plymouth",
    "offsetHours": -4,
    "aqi": 58
  },
  "Martinique": {
    "capital": "Fort-de-France",
    "offsetHours": -4,
    "aqi": 57
  },
  "Mauritius": {
    "capital": "Port Louis",
    "offsetHours": 4,
    "aqi": 23
  },
  "Malaysia": {
    "capital": "Kuala Lumpur",
    "offsetHours": 8,
    "aqi": 82
  },
  "Malawi": {
    "capital": "Lilongwe",
    "offsetHours": 2,
    "aqi": 63
  },
  "Mayotte": {
    "capital": "Mamoudzou",
    "offsetHours": 3,
    "aqi": 12
  },
  "Niger": {
    "capital": "Niamey",
    "offsetHours": 1,
    "aqi": 50
  },
  "Namibia": {
    "capital": "Windhoek",
    "offsetHours": 2,
    "aqi": 27
  },
  "New Caledonia": {
    "capital": "Nouméa",
    "offsetHours": 11,
    "aqi": 20
  },
  "Nigeria": {
    "capital": "Abuja",
    "offsetHours": 1,
    "aqi": 49
  },
  "Norfolk Island": {
    "capital": "Kingston",
    "offsetHours": 11,
    "aqi": 9
  },
  "Nicaragua": {
    "capital": "Managua",
    "offsetHours": -6,
    "aqi": 25
  },
  "Niue": {
    "capital": "Alofi",
    "offsetHours": -11,
    "aqi": 9
  },
  "Netherlands": {
    "capital": "Amsterdam",
    "offsetHours": 2,
    "aqi": 29
  },
  "Norway": {
    "capital": "Oslo",
    "offsetHours": 2,
    "aqi": 28
  },
  "Nepal": {
    "capital": "Kathmandu",
    "offsetHours": 5.75,
    "aqi": null
  },
  "Nauru": {
    "capital": "Yaren",
    "offsetHours": 12,
    "aqi": 16
  },
  "New Zealand": {
    "capital": "Wellington",
    "offsetHours": 12,
    "aqi": 7
  },
  "Oman": {
    "capital": "Muscat",
    "offsetHours": 4,
    "aqi": 116
  },
  "Pakistan": {
    "capital": "Islamabad",
    "offsetHours": 5,
    "aqi": 195
  },
  "Panama": {
    "capital": "Panama City",
    "offsetHours": -5,
    "aqi": 55
  },
  "Pitcairn Islands": {
    "capital": "Adamstown",
    "offsetHours": -8,
    "aqi": 97
  },
  "Peru": {
    "capital": "Lima",
    "offsetHours": -5,
    "aqi": 157
  },
  "Philippines": {
    "capital": "Manila",
    "offsetHours": 8,
    "aqi": 10
  },
  "Palau": {
    "capital": "Ngerulmud",
    "offsetHours": 9,
    "aqi": 55
  },
  "Papua New Guinea": {
    "capital": "Port Moresby",
    "offsetHours": 10,
    "aqi": 20
  },
  "Poland": {
    "capital": "Warsaw",
    "offsetHours": 2,
    "aqi": 39
  },
  "Puerto Rico": {
    "capital": "San Juan",
    "offsetHours": -4,
    "aqi": 66
  },
  "North Korea": {
    "capital": "Pyongyang",
    "offsetHours": 9,
    "aqi": 43
  },
  "Paraguay": {
    "capital": "Asunción",
    "offsetHours": -3,
    "aqi": 23
  },
  "Portugal": {
    "capital": "Lisbon",
    "offsetHours": 1,
    "aqi": 55
  },
  "Palestine": {
    "capital": "Ramallah",
    "offsetHours": 3,
    "aqi": 54
  },
  "French Polynesia": {
    "capital": "Papeetē",
    "offsetHours": -10,
    "aqi": 9
  },
  "Qatar": {
    "capital": "Doha",
    "offsetHours": 3,
    "aqi": 76
  },
  "Réunion": {
    "capital": "Saint-Denis",
    "offsetHours": 4,
    "aqi": 23
  },
  "Romania": {
    "capital": "Bucharest",
    "offsetHours": 3,
    "aqi": 18
  },
  "Russia": {
    "capital": "Moscow",
    "offsetHours": 3,
    "aqi": 17
  },
  "Saudi Arabia": {
    "capital": "Riyadh",
    "offsetHours": 3,
    "aqi": 57
  },
  "Sudan": {
    "capital": "Khartoum",
    "offsetHours": 2,
    "aqi": 23
  },
  "Rwanda": {
    "capital": "Kigali",
    "offsetHours": 2,
    "aqi": 48
  },
  "Senegal": {
    "capital": "Dakar",
    "offsetHours": 0,
    "aqi": 30
  },
  "South Georgia": {
    "capital": "King Edward Point",
    "offsetHours": -2,
    "aqi": 30
  },
  "Singapore": {
    "capital": "Singapore",
    "offsetHours": 8,
    "aqi": 61
  },
  "Solomon Islands": {
    "capital": "Honiara",
    "offsetHours": 11,
    "aqi": 16
  },
  "Svalbard and Jan Mayen": {
    "capital": "Longyearbyen",
    "offsetHours": 2,
    "aqi": 6
  },
  "Sierra Leone": {
    "capital": "Freetown",
    "offsetHours": 0,
    "aqi": 38
  },
  "El Salvador": {
    "capital": "San Salvador",
    "offsetHours": -6,
    "aqi": 25
  },
  "Somalia": {
    "capital": "Mogadishu",
    "offsetHours": 3,
    "aqi": 48
  },
  "Saint Pierre and Miquelon": {
    "capital": "Saint-Pierre",
    "offsetHours": -2,
    "aqi": 36
  },
  "Serbia": {
    "capital": "Belgrade",
    "offsetHours": 2,
    "aqi": 35
  },
  "São Tomé and Príncipe": {
    "capital": "São Tomé",
    "offsetHours": 0,
    "aqi": 291
  },
  "South Sudan": {
    "capital": "Juba",
    "offsetHours": 2,
    "aqi": 48
  },
  "Suriname": {
    "capital": "Paramaribo",
    "offsetHours": -3,
    "aqi": 13
  },
  "Slovenia": {
    "capital": "Ljubljana",
    "offsetHours": 2,
    "aqi": 17
  },
  "Slovakia": {
    "capital": "Bratislava",
    "offsetHours": 2,
    "aqi": 17
  },
  "Sweden": {
    "capital": "Stockholm",
    "offsetHours": 2,
    "aqi": 26
  },
  "Eswatini": {
    "capital": "Lobamba",
    "offsetHours": 2,
    "aqi": 153
  },
  "Sint Maarten": {
    "capital": "Philipsburg",
    "offsetHours": -4,
    "aqi": 58
  },
  "Seychelles": {
    "capital": "Victoria",
    "offsetHours": -3,
    "aqi": 20
  },
  "Syria": {
    "capital": "Damascus",
    "offsetHours": 3,
    "aqi": 18
  },
  "Turks and Caicos Islands": {
    "capital": "Cockburn Town",
    "offsetHours": -4,
    "aqi": 51
  },
  "Togo": {
    "capital": "Lomé",
    "offsetHours": 0,
    "aqi": 50
  },
  "Chad": {
    "capital": "N'Djamena",
    "offsetHours": 1,
    "aqi": 49
  },
  "Thailand": {
    "capital": "Bangkok",
    "offsetHours": 7,
    "aqi": 42
  },
  "Tajikistan": {
    "capital": "Dushanbe",
    "offsetHours": 5,
    "aqi": 74
  },
  "Turkmenistan": {
    "capital": "Ashgabat",
    "offsetHours": 5,
    "aqi": 114
  },
  "Timor-Leste": {
    "capital": "Dili",
    "offsetHours": 9,
    "aqi": 55
  },
  "Tonga": {
    "capital": "Nuku'alofa",
    "offsetHours": 13,
    "aqi": 9
  },
  "Trinidad and Tobago": {
    "capital": "Port of Spain",
    "offsetHours": -4,
    "aqi": 76
  },
  "Tunisia": {
    "capital": "Tunis",
    "offsetHours": 1,
    "aqi": 51
  },
  "Türkiye": {
    "capital": "Ankara",
    "offsetHours": 3,
    "aqi": 58
  },
  "Tuvalu": {
    "capital": "Funafuti",
    "offsetHours": 12,
    "aqi": 9
  },
  "Taiwan": {
    "capital": "Taipei",
    "offsetHours": 8,
    "aqi": 38
  },
  "Tanzania": {
    "capital": "Dodoma",
    "offsetHours": 3,
    "aqi": 48
  },
  "Uganda": {
    "capital": "Kampala",
    "offsetHours": 3,
    "aqi": 48
  },
  "Ukraine": {
    "capital": "Kyiv",
    "offsetHours": 3,
    "aqi": 27
  },
  "Uruguay": {
    "capital": "Montevideo",
    "offsetHours": -3,
    "aqi": 23
  },
  "Uzbekistan": {
    "capital": "Tashkent",
    "offsetHours": 5,
    "aqi": 53
  },
  "United States": {
    "capital": "Washington D.C.",
    "offsetHours": -4,
    "aqi": 33
  },
  "Vatican City": {
    "capital": "Vatican City",
    "offsetHours": 2,
    "aqi": 34
  },
  "Saint Vincent and the Grenadines": {
    "capital": "Kingstown",
    "offsetHours": -4,
    "aqi": 76
  },
  "Venezuela": {
    "capital": "Caracas",
    "offsetHours": -4,
    "aqi": 69
  },
  "British Virgin Islands": {
    "capital": "Road Town",
    "offsetHours": -4,
    "aqi": 58
  },
  "United States Virgin Islands": {
    "capital": "Charlotte Amalie",
    "offsetHours": -4,
    "aqi": 66
  },
  "Vietnam": {
    "capital": "Hanoi",
    "offsetHours": 7,
    "aqi": 100
  },
  "Vanuatu": {
    "capital": "Port Vila",
    "offsetHours": 11,
    "aqi": 9
  },
  "Wallis and Futuna": {
    "capital": "Mata-Utu",
    "offsetHours": 12,
    "aqi": 9
  },
  "Samoa": {
    "capital": "Apia",
    "offsetHours": 13,
    "aqi": 9
  },
  "Yemen": {
    "capital": "Sana'a",
    "offsetHours": 3,
    "aqi": 68
  },
  "South Africa": {
    "capital": "Pretoria",
    "offsetHours": 2,
    "aqi": 107
  },
  "Zambia": {
    "capital": "Lusaka",
    "offsetHours": 2,
    "aqi": 291
  },
  "Zimbabwe": {
    "capital": "Harare",
    "offsetHours": 2,
    "aqi": 63
  }
};
