// AUTO-GENERATED by scripts/fetch-salaries.mjs — do not edit by hand.
// Source: Adzuna Jobs API (https://developer.adzuna.com). avgAnnual is the most
// recent monthly average advertised salary across all roles; benchmarkMedian is
// the median salary band for "software engineer" so figures are comparable across
// countries. Only Adzuna-supported countries appear here. Regenerate with:
// ADZUNA_APP_ID=... ADZUNA_APP_KEY=... node scripts/fetch-salaries.mjs

export interface CountrySalary {
  /** Local currency of the figures (ISO 4217). */
  currency: string;
  /** Most recent monthly average advertised salary, annualised, or null. */
  avgAnnual: number | null;
  /** Month the average is from, e.g. "2026-05". */
  avgMonth: string | null;
  /** Benchmark role the median is computed for. */
  benchmarkRole: string;
  /** Median salary band floor for the benchmark role, or null. */
  benchmarkMedian: number | null;
  /** Number of postings behind the median. */
  sampleSize: number | null;
  source: string;
}

export const SALARIES_UPDATED_AT = "2026-07-07";

export const COUNTRY_SALARIES: Record<string, CountrySalary> = {
  "United States": {
    "currency": "USD",
    "avgAnnual": 81656,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 140000,
    "sampleSize": 25103,
    "source": "https://www.adzuna.com"
  },
  "Canada": {
    "currency": "CAD",
    "avgAnnual": 71306,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 120000,
    "sampleSize": 1332,
    "source": "https://www.adzuna.com"
  },
  "United Kingdom": {
    "currency": "GBP",
    "avgAnnual": 43053,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 60000,
    "sampleSize": 2819,
    "source": "https://www.adzuna.com"
  },
  "Germany": {
    "currency": "EUR",
    "avgAnnual": 44186,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 70000,
    "sampleSize": 170,
    "source": "https://www.adzuna.com"
  },
  "France": {
    "currency": "EUR",
    "avgAnnual": 39685,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 50000,
    "sampleSize": 177,
    "source": "https://www.adzuna.com"
  },
  "Italy": {
    "currency": "EUR",
    "avgAnnual": 22364,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 40000,
    "sampleSize": 28,
    "source": "https://www.adzuna.com"
  },
  "Spain": {
    "currency": "EUR",
    "avgAnnual": 46256,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 70000,
    "sampleSize": 197,
    "source": "https://www.adzuna.com"
  },
  "Netherlands": {
    "currency": "EUR",
    "avgAnnual": 44584,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 50000,
    "sampleSize": 676,
    "source": "https://www.adzuna.com"
  },
  "Austria": {
    "currency": "EUR",
    "avgAnnual": 38497,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": null,
    "sampleSize": null,
    "source": "https://www.adzuna.com"
  },
  "Switzerland": {
    "currency": "CHF",
    "avgAnnual": 72080,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": null,
    "sampleSize": null,
    "source": "https://www.adzuna.com"
  },
  "Poland": {
    "currency": "PLN",
    "avgAnnual": 146784,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 180000,
    "sampleSize": 498,
    "source": "https://www.adzuna.com"
  },
  "Singapore": {
    "currency": "SGD",
    "avgAnnual": 7774,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 0,
    "sampleSize": 1214,
    "source": "https://www.adzuna.com"
  },
  "Brazil": {
    "currency": "BRL",
    "avgAnnual": 32235,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": null,
    "sampleSize": null,
    "source": "https://www.adzuna.com"
  },
  "Mexico": {
    "currency": "MXN",
    "avgAnnual": 172300,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 70000,
    "sampleSize": 32,
    "source": "https://www.adzuna.com"
  },
  "Australia": {
    "currency": "AUD",
    "avgAnnual": 107005,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 140000,
    "sampleSize": 170,
    "source": "https://www.adzuna.com"
  },
  "New Zealand": {
    "currency": "NZD",
    "avgAnnual": 101023,
    "avgMonth": "2026-06",
    "benchmarkRole": "software engineer",
    "benchmarkMedian": 125000,
    "sampleSize": 31,
    "source": "https://www.adzuna.com"
  }
};
