// AUTO-GENERATED by scripts/fetch-rates.mjs — do not edit by hand.
// Source: exchangerate-api.com (Standard endpoint, base USD).
// Regenerate with: EXCHANGERATE_API_KEY=... node scripts/fetch-rates.mjs
//
// Committed offline snapshot so the app never calls the rate-limited API
// (1,500 req / 30 days) at request time. All conversions are derived locally
// from the USD base: 1 FROM = rates[TO] / rates[FROM] TO.
//
// Placeholder until the first live fetch runs — empty rates degrade gracefully
// (the currency line is simply hidden).

export interface ExchangeRateSnapshot {
  base: string;
  updatedAt: string;
  rates: Record<string, number>;
}

export const EXCHANGE_RATES: ExchangeRateSnapshot = {
  base: "USD",
  updatedAt: "",
  rates: {},
};
