import type { ReloInput, ReloPlan, VisaSummary } from "@/lib/types";

/** Human-readable route line, e.g. "Lisbon, Portugal -> Tbilisi, Georgia". */
function routeLine(input: ReloInput): string {
  const from = input.fromCity?.trim()
    ? `${input.fromCity.trim()}, ${input.fromCountry}`
    : input.fromCountry;
  const to = input.toCity?.trim()
    ? `${input.toCity.trim()}, ${input.toCountry}`
    : input.toCountry;
  return `${from} -> ${to}`;
}

/**
 * Render a relocation plan as GitHub-flavoured Markdown: a checklist the mover
 * can keep, edit, or paste into their own notes. Kept DOM-free so it can be
 * unit-tested and reused server-side if ever needed.
 */
export function planToMarkdown(
  input: ReloInput,
  plan: ReloPlan,
  visa: VisaSummary | null,
): string {
  const lines: string[] = [];
  const route = routeLine(input);

  lines.push(`# Relocation plan: ${route}`);
  lines.push("");

  if (visa?.label) {
    lines.push(`**Visa:** ${visa.label}`);
    lines.push("");
  }
  if (plan.destinationSummary) {
    lines.push(plan.destinationSummary);
    lines.push("");
  }
  if (plan.feasibility?.note) {
    const flag =
      plan.feasibility.level === "blocked"
        ? "This move may not be possible right now"
        : "Important restrictions to check first";
    lines.push(`> **${flag}.** ${plan.feasibility.note}`);
    lines.push("");
  }

  for (const phase of plan.phases) {
    if (phase.items.length === 0) continue;
    lines.push(`## ${phase.title}`);
    lines.push("");
    for (const item of phase.items) {
      const meta = [item.category, item.deadline, item.estimate]
        .filter((v): v is string => Boolean(v && v.trim()))
        .join(" · ");
      lines.push(`- [ ] **${item.title}**${meta ? ` — _${meta}_` : ""}`);
      if (item.why) lines.push(`  - ${item.why}`);
      for (const step of item.steps ?? []) lines.push(`  - ${step}`);
      if (item.documents?.length)
        lines.push(`  - Documents: ${item.documents.join(", ")}`);
      if (item.commonMistake)
        lines.push(`  - Common mistake: ${item.commonMistake}`);
      if (item.url) lines.push(`  - Source: ${item.url}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`Generated by Reloka · https://reloka.to`);
  lines.push("");

  return lines.join("\n");
}

/** Safe kebab-case file stem from the route, e.g. "lisbon-to-tbilisi". */
export function planFileStem(input: ReloInput): string {
  const from = (input.fromCity?.trim() || input.fromCountry || "home")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  const to = (input.toCity?.trim() || input.toCountry || "destination")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return `reloka-${from}-to-${to}`;
}
