// Offline fetcher for exchange rates (exchangerate-api.com v6).
//
// WHY OFFLINE: same rationale as fetch-advisory.mjs. The free tier allows
// 1,500 requests / 30 days. We only need ONE request: the Standard endpoint
// returns conversion rates from a single base currency (USD) to every other
// currency. We commit that as a static snapshot (src/lib/exchangeRates.generated.ts)
// and the app converts any origin -> destination locally from the USD base
// (rate[to] / rate[from]). No live calls at request time.
//
// Usage: EXCHANGERATE_API_KEY=... node scripts/fetch-rates.mjs

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const KEY = process.env.EXCHANGERATE_API_KEY;
const BASE_CODE = "USD";

if (!KEY) {
  console.error("Missing EXCHANGERATE_API_KEY environment variable.");
  process.exit(1);
}

async function main() {
  const url = `https://v6.exchangerate-api.com/v6/${KEY}/latest/${BASE_CODE}`;
  const res = await fetch(url);
  const json = await res.json();
  if (!res.ok || json.result !== "success") {
    throw new Error(
      `exchangerate-api error: HTTP ${res.status} ${json["error-type"] ?? json.result ?? ""}`,
    );
  }

  const rates = json.conversion_rates ?? {};
  // Round to 6 significant places to keep the snapshot compact and readable.
  const conversionRates = {};
  for (const [code, rate] of Object.entries(rates)) {
    if (typeof rate === "number" && Number.isFinite(rate)) {
      conversionRates[code] = Number(rate.toPrecision(8));
    }
  }

  const updatedAt = json.time_last_update_utc
    ? new Date(json.time_last_update_utc).toISOString().slice(0, 10)
    : new Date().toISOString().slice(0, 10);

  const header = `// AUTO-GENERATED by scripts/fetch-rates.mjs — do not edit by hand.
// Source: exchangerate-api.com (Standard endpoint, base ${BASE_CODE}).
// Regenerate with: EXCHANGERATE_API_KEY=... node scripts/fetch-rates.mjs
//
// Committed offline snapshot so the app never calls the rate-limited API
// (1,500 req / 30 days) at request time. All conversions are derived locally
// from the ${BASE_CODE} base: 1 FROM = rates[TO] / rates[FROM] TO.

export interface ExchangeRateSnapshot {
  base: string;
  updatedAt: string;
  rates: Record<string, number>;
}

export const EXCHANGE_RATES: ExchangeRateSnapshot = {
  base: ${JSON.stringify(BASE_CODE)},
  updatedAt: ${JSON.stringify(updatedAt)},
  rates: ${JSON.stringify(conversionRates, null, 2)},
};
`;

  writeFileSync(join(ROOT, "src/lib/exchangeRates.generated.ts"), header);
  console.log(
    `Wrote ${Object.keys(conversionRates).length} rates (base ${BASE_CODE}, updated ${updatedAt}) to src/lib/exchangeRates.generated.ts`,
  );
}

main();
